-- SEMANA 3 · Rutinas diarias y verbos comunes · 63 palabras
insert into words (week, section, en, es) values
(3, 'Rutina diaria', 'to wake up', 'despertarse'),
(3, 'Rutina diaria', 'to get up', 'levantarse'),
(3, 'Rutina diaria', 'to take a shower', 'ducharse'),
(3, 'Rutina diaria', 'to brush your teeth', 'cepillarse los dientes'),
(3, 'Rutina diaria', 'to get dressed', 'vestirse'),
(3, 'Rutina diaria', 'to have breakfast', 'desayunar'),
(3, 'Rutina diaria', 'to have lunch', 'almorzar'),
(3, 'Rutina diaria', 'to have dinner', 'cenar'),
(3, 'Rutina diaria', 'to go to work', 'ir al trabajo'),
(3, 'Rutina diaria', 'to go to school', 'ir a la escuela'),
(3, 'Rutina diaria', 'to start', 'empezar'),
(3, 'Rutina diaria', 'to finish', 'terminar'),
(3, 'Rutina diaria', 'to work', 'trabajar'),
(3, 'Rutina diaria', 'to study', 'estudiar'),
(3, 'Rutina diaria', 'to read', 'leer'),
(3, 'Rutina diaria', 'to write', 'escribir'),
(3, 'Rutina diaria', 'to listen', 'escuchar'),
(3, 'Rutina diaria', 'to watch TV', 'ver la tele'),
(3, 'Rutina diaria', 'to cook', 'cocinar'),
(3, 'Rutina diaria', 'to clean', 'limpiar'),
(3, 'Rutina diaria', 'to wash', 'lavar'),
(3, 'Actividades del día', 'to do homework', 'hacer los deberes'),
(3, 'Actividades del día', 'to go to bed', 'acostarse'),
(3, 'Actividades del día', 'to sleep', 'dormir'),
(3, 'Actividades del día', 'to eat', 'comer'),
(3, 'Actividades del día', 'to drink', 'beber'),
(3, 'Actividades del día', 'to walk', 'caminar'),
(3, 'Actividades del día', 'to run', 'correr'),
(3, 'Actividades del día', 'to drive', 'conducir'),
(3, 'Actividades del día', 'to take the bus', 'tomar el bus'),
(3, 'Actividades del día', 'to arrive', 'llegar'),
(3, 'Actividades del día', 'to leave', 'salir/irse'),
(3, 'Actividades del día', 'to come back', 'volver'),
(3, 'Actividades del día', 'to rest', 'descansar'),
(3, 'Actividades del día', 'to play', 'jugar'),
(3, 'Actividades del día', 'to open', 'abrir'),
(3, 'Actividades del día', 'to close', 'cerrar'),
(3, 'Actividades del día', 'to buy', 'comprar'),
(3, 'Actividades del día', 'to sell', 'vender'),
(3, 'Actividades del día', 'to help', 'ayudar'),
(3, 'Actividades del día', 'to call', 'llamar'),
(3, 'Actividades del día', 'to send', 'enviar'),
(3, 'Verbos comunes y frecuencia', 'to use', 'usar'),
(3, 'Verbos comunes y frecuencia', 'to need', 'necesitar'),
(3, 'Verbos comunes y frecuencia', 'to want', 'querer'),
(3, 'Verbos comunes y frecuencia', 'to like', 'gustar'),
(3, 'Verbos comunes y frecuencia', 'to love', 'amar/encantar'),
(3, 'Verbos comunes y frecuencia', 'to hate', 'odiar'),
(3, 'Verbos comunes y frecuencia', 'to know', 'saber/conocer'),
(3, 'Verbos comunes y frecuencia', 'to think', 'pensar'),
(3, 'Verbos comunes y frecuencia', 'to say', 'decir'),
(3, 'Verbos comunes y frecuencia', 'to tell', 'contar (a alguien)'),
(3, 'Verbos comunes y frecuencia', 'to give', 'dar'),
(3, 'Verbos comunes y frecuencia', 'to take', 'tomar/coger'),
(3, 'Verbos comunes y frecuencia', 'to make', 'hacer (crear)'),
(3, 'Verbos comunes y frecuencia', 'to do', 'hacer'),
(3, 'Verbos comunes y frecuencia', 'early', 'temprano'),
(3, 'Verbos comunes y frecuencia', 'late', 'tarde'),
(3, 'Verbos comunes y frecuencia', 'always', 'siempre'),
(3, 'Verbos comunes y frecuencia', 'usually', 'normalmente'),
(3, 'Verbos comunes y frecuencia', 'sometimes', 'a veces'),
(3, 'Verbos comunes y frecuencia', 'never', 'nunca'),
(3, 'Verbos comunes y frecuencia', 'every day', 'todos los días');
