-- SEMANA 19 · Experiencias de vida · 70 palabras
insert into words (week, section, en, es) values
(19, 'Experiencias y frecuencia', 'adventure', 'aventura'),
(19, 'Experiencias y frecuencia', 'to try new things', 'probar cosas nuevas'),
(19, 'Experiencias y frecuencia', 'ever', 'alguna vez'),
(19, 'Experiencias y frecuencia', 'already', 'ya'),
(19, 'Experiencias y frecuencia', 'yet', 'todavía/aún'),
(19, 'Experiencias y frecuencia', 'just (recently)', 'recién/acabar de'),
(19, 'Experiencias y frecuencia', 'so far', 'hasta ahora'),
(19, 'Experiencias y frecuencia', 'once', 'una vez'),
(19, 'Experiencias y frecuencia', 'twice', 'dos veces'),
(19, 'Experiencias y frecuencia', 'several times', 'varias veces'),
(19, 'Experiencias y frecuencia', 'to have been to', 'haber estado en'),
(19, 'Experiencias y frecuencia', 'foreign', 'extranjero (adj)'),
(19, 'Experiencias y frecuencia', 'culture', 'cultura'),
(19, 'Experiencias y frecuencia', 'custom', 'costumbre'),
(19, 'Experiencias y frecuencia', 'tradition', 'tradición'),
(19, 'Experiencias y frecuencia', 'festival', 'festival'),
(19, 'Experiencias y frecuencia', 'to take part', 'participar'),
(19, 'Experiencias y frecuencia', 'competition', 'competición'),
(19, 'Experiencias y frecuencia', 'contest', 'concurso'),
(19, 'Experiencias y frecuencia', 'to volunteer', 'hacer voluntariado'),
(19, 'Experiencias y frecuencia', 'volunteer', 'voluntario'),
(19, 'Experiencias y frecuencia', 'charity', 'organización benéfica'),
(19, 'Experiencias y frecuencia', 'to donate', 'donar'),
(19, 'Experiencias y frecuencia', 'to help out', 'echar una mano'),
(19, 'Emociones y reacciones', 'to explore', 'explorar'),
(19, 'Emociones y reacciones', 'amazing', 'increíble'),
(19, 'Emociones y reacciones', 'incredible', 'increíble (sinónimo)'),
(19, 'Emociones y reacciones', 'unforgettable', 'inolvidable'),
(19, 'Emociones y reacciones', 'unusual', 'inusual'),
(19, 'Emociones y reacciones', 'strange', 'extraño'),
(19, 'Emociones y reacciones', 'weird', 'raro'),
(19, 'Emociones y reacciones', 'scary', 'aterrador'),
(19, 'Emociones y reacciones', 'frightening', 'espantoso'),
(19, 'Emociones y reacciones', 'dangerous', 'peligroso'),
(19, 'Emociones y reacciones', 'safe', 'seguro (sin peligro)'),
(19, 'Emociones y reacciones', 'brave', 'valiente'),
(19, 'Emociones y reacciones', 'afraid', 'asustado'),
(19, 'Emociones y reacciones', 'fear', 'miedo'),
(19, 'Emociones y reacciones', 'to be scared', 'tener miedo'),
(19, 'Emociones y reacciones', 'to dare', 'atreverse'),
(19, 'Emociones y reacciones', 'challenge', 'reto'),
(19, 'Emociones y reacciones', 'to face', 'enfrentar'),
(19, 'Emociones y reacciones', 'to overcome', 'superar'),
(19, 'Emociones y reacciones', 'proud', 'orgulloso'),
(19, 'Emociones y reacciones', 'pride', 'orgullo'),
(19, 'Emociones y reacciones', 'to regret', 'arrepentirse'),
(19, 'Emociones y reacciones', 'mistake', 'error'),
(19, 'Emociones y reacciones', 'to make a mistake', 'cometer un error'),
(19, 'Retos y aventuras', 'lesson', 'lección'),
(19, 'Retos y aventuras', 'to learn', 'aprender'),
(19, 'Retos y aventuras', 'to teach', 'enseñar'),
(19, 'Retos y aventuras', 'skydiving', 'paracaidismo'),
(19, 'Retos y aventuras', 'bungee jumping', 'puenting'),
(19, 'Retos y aventuras', 'to climb a mountain', 'escalar una montaña'),
(19, 'Retos y aventuras', 'marathon', 'maratón'),
(19, 'Retos y aventuras', 'to run a marathon', 'correr un maratón'),
(19, 'Retos y aventuras', 'to meet someone famous', 'conocer a alguien famoso'),
(19, 'Retos y aventuras', 'to win a prize', 'ganar un premio'),
(19, 'Retos y aventuras', 'luck', 'suerte'),
(19, 'Retos y aventuras', 'lucky', 'afortunado'),
(19, 'Retos y aventuras', 'unlucky', 'desafortunado'),
(19, 'Retos y aventuras', 'coincidence', 'casualidad'),
(19, 'Retos y aventuras', 'to tell a story', 'contar una historia'),
(19, 'Retos y aventuras', 'once in a lifetime', 'una vez en la vida'),
(19, 'Retos y aventuras', 'to try exotic food', 'probar comida exótica'),
(19, 'Retos y aventuras', 'to get a tattoo', 'hacerse un tatuaje'),
(19, 'Retos y aventuras', 'to live abroad', 'vivir en el extranjero'),
(19, 'Retos y aventuras', 'to learn a language', 'aprender un idioma'),
(19, 'Retos y aventuras', 'to ride a horse', 'montar a caballo'),
(19, 'Retos y aventuras', 'to see the sunrise', 'ver el amanecer');
