-- SEMANA 18 · Citas, eventos e invitaciones · 69 palabras
-- Nota: el título original decía "70 palabras"; transcribiendo la tabla con cuidado
-- solo conté 69. Si tienes el listado en texto plano, dime y reviso la que falte.
insert into words (week, section, en, es) values
(18, 'Invitaciones y llegar a tiempo', 'invitation', 'invitación'),
(18, 'Invitaciones y llegar a tiempo', 'celebration', 'celebración'),
(18, 'Invitaciones y llegar a tiempo', 'ceremony', 'ceremonia'),
(18, 'Invitaciones y llegar a tiempo', 'anniversary', 'aniversario'),
(18, 'Invitaciones y llegar a tiempo', 'date (romantic)', 'cita (romántica)'),
(18, 'Invitaciones y llegar a tiempo', 'to make an appointment', 'pedir cita'),
(18, 'Invitaciones y llegar a tiempo', 'to meet up', 'quedar (verse)'),
(18, 'Invitaciones y llegar a tiempo', 'meeting point', 'punto de encuentro'),
(18, 'Invitaciones y llegar a tiempo', 'to arrive on time', 'llegar puntual'),
(18, 'Invitaciones y llegar a tiempo', 'to be late', 'llegar tarde'),
(18, 'Invitaciones y llegar a tiempo', 'to wait', 'esperar (aguardar)'),
(18, 'Invitaciones y llegar a tiempo', 'to pick someone up', 'recoger a alguien'),
(18, 'Invitaciones y llegar a tiempo', 'to join', 'unirse'),
(18, 'Invitaciones y llegar a tiempo', 'to come along', 'acompañar'),
(18, 'Invitaciones y llegar a tiempo', 'to bring', 'traer'),
(18, 'Invitaciones y llegar a tiempo', 'to accept', 'aceptar'),
(18, 'Invitaciones y llegar a tiempo', 'to refuse', 'rechazar'),
(18, 'Invitaciones y llegar a tiempo', 'to turn down', 'rechazar (una oferta)'),
(18, 'Invitaciones y llegar a tiempo', 'to suggest', 'sugerir'),
(18, 'Invitaciones y llegar a tiempo', 'suggestion', 'sugerencia'),
(18, 'Invitaciones y llegar a tiempo', 'to propose', 'proponer'),
(18, 'Invitaciones y llegar a tiempo', 'would you like...?', '¿te gustaría...?'),
(18, 'Invitaciones y llegar a tiempo', 'how about...?', '¿qué tal si...?'),
(18, 'Presentaciones y el evento', 'to agree', 'estar de acuerdo'),
(18, 'Presentaciones y el evento', 'to disagree', 'no estar de acuerdo'),
(18, 'Presentaciones y el evento', 'available', 'disponible'),
(18, 'Presentaciones y el evento', 'diary', 'agenda'),
(18, 'Presentaciones y el evento', 'to note down', 'anotar'),
(18, 'Presentaciones y el evento', 'reminder', 'recordatorio'),
(18, 'Presentaciones y el evento', 'to remind', 'recordar (a alguien)'),
(18, 'Presentaciones y el evento', 'to look forward to', 'tener ganas de'),
(18, 'Presentaciones y el evento', 'excited', 'emocionado'),
(18, 'Presentaciones y el evento', 'nervous', 'nervioso'),
(18, 'Presentaciones y el evento', 'to get ready', 'arreglarse'),
(18, 'Presentaciones y el evento', 'dress code', 'código de vestimenta'),
(18, 'Presentaciones y el evento', 'formal', 'formal'),
(18, 'Presentaciones y el evento', 'casual', 'informal'),
(18, 'Presentaciones y el evento', 'venue', 'lugar del evento'),
(18, 'Presentaciones y el evento', 'entrance', 'entrada (lugar)'),
(18, 'Presentaciones y el evento', 'exit', 'salida (lugar)'),
(18, 'Presentaciones y el evento', 'crowd', 'multitud'),
(18, 'Presentaciones y el evento', 'to show up', 'aparecer/presentarse'),
(18, 'Presentaciones y el evento', 'to introduce someone', 'presentar a alguien'),
(18, 'Presentaciones y el evento', 'to greet', 'saludar'),
(18, 'Presentaciones y el evento', 'hug', 'abrazo'),
(18, 'Presentaciones y el evento', 'to hug', 'abrazar'),
(18, 'Presentaciones y el evento', 'kiss', 'beso'),
(18, 'Conversación y despedidas', 'to kiss', 'besar'),
(18, 'Conversación y despedidas', 'handshake', 'apretón de manos'),
(18, 'Conversación y despedidas', 'small talk', 'charla trivial'),
(18, 'Conversación y despedidas', 'conversation', 'conversación'),
(18, 'Conversación y despedidas', 'topic', 'tema'),
(18, 'Conversación y despedidas', 'to have a good time', 'pasarlo bien'),
(18, 'Conversación y despedidas', 'atmosphere', 'ambiente'),
(18, 'Conversación y despedidas', 'surprise', 'sorpresa'),
(18, 'Conversación y despedidas', 'to surprise', 'sorprender'),
(18, 'Conversación y despedidas', 'surprise party', 'fiesta sorpresa'),
(18, 'Conversación y despedidas', 'congratulations', 'felicidades'),
(18, 'Conversación y despedidas', 'to congratulate', 'felicitar'),
(18, 'Conversación y despedidas', 'toast (drink)', 'brindis'),
(18, 'Conversación y despedidas', 'cheers', 'salud (brindis)'),
(18, 'Conversación y despedidas', 'farewell', 'despedida'),
(18, 'Conversación y despedidas', 'to say goodbye', 'despedirse'),
(18, 'Conversación y despedidas', 'to reschedule', 'reprogramar'),
(18, 'Conversación y despedidas', 'see you there', 'nos vemos allí'),
(18, 'Conversación y despedidas', 'get-together', 'reunión informal'),
(18, 'Conversación y despedidas', 'to hang up', 'colgar (el teléfono)'),
(18, 'Conversación y despedidas', 'to text back', 'responder al mensaje'),
(18, 'Conversación y despedidas', 'to call back', 'devolver la llamada');
