-- SEMANA 4 · La hora, días, meses y fechas · 63 palabras
insert into words (week, section, en, es) values
(4, 'La hora y momentos del día', 'time', 'hora/tiempo'),
(4, 'La hora y momentos del día', 'hour', 'hora'),
(4, 'La hora y momentos del día', 'minute', 'minuto'),
(4, 'La hora y momentos del día', 'second', 'segundo'),
(4, 'La hora y momentos del día', 'o''clock', 'en punto'),
(4, 'La hora y momentos del día', 'half past', 'y media'),
(4, 'La hora y momentos del día', 'quarter past', 'y cuarto'),
(4, 'La hora y momentos del día', 'quarter to', 'menos cuarto'),
(4, 'La hora y momentos del día', 'noon', 'mediodía'),
(4, 'La hora y momentos del día', 'midnight', 'medianoche'),
(4, 'La hora y momentos del día', 'morning', 'mañana'),
(4, 'La hora y momentos del día', 'afternoon', 'tarde'),
(4, 'La hora y momentos del día', 'evening', 'tarde-noche'),
(4, 'La hora y momentos del día', 'night', 'noche'),
(4, 'La hora y momentos del día', 'today', 'hoy'),
(4, 'La hora y momentos del día', 'tomorrow', 'mañana (día siguiente)'),
(4, 'La hora y momentos del día', 'yesterday', 'ayer'),
(4, 'La hora y momentos del día', 'week', 'semana'),
(4, 'La hora y momentos del día', 'weekend', 'fin de semana'),
(4, 'La hora y momentos del día', 'month', 'mes'),
(4, 'La hora y momentos del día', 'year', 'año'),
(4, 'Días y meses', 'Monday', 'lunes'),
(4, 'Días y meses', 'Tuesday', 'martes'),
(4, 'Días y meses', 'Wednesday', 'miércoles'),
(4, 'Días y meses', 'Thursday', 'jueves'),
(4, 'Días y meses', 'Friday', 'viernes'),
(4, 'Días y meses', 'Saturday', 'sábado'),
(4, 'Días y meses', 'Sunday', 'domingo'),
(4, 'Días y meses', 'January', 'enero'),
(4, 'Días y meses', 'February', 'febrero'),
(4, 'Días y meses', 'March', 'marzo'),
(4, 'Días y meses', 'April', 'abril'),
(4, 'Días y meses', 'May', 'mayo'),
(4, 'Días y meses', 'June', 'junio'),
(4, 'Días y meses', 'July', 'julio'),
(4, 'Días y meses', 'August', 'agosto'),
(4, 'Días y meses', 'September', 'septiembre'),
(4, 'Días y meses', 'October', 'octubre'),
(4, 'Días y meses', 'November', 'noviembre'),
(4, 'Días y meses', 'December', 'diciembre'),
(4, 'Días y meses', 'spring', 'primavera'),
(4, 'Días y meses', 'summer', 'verano'),
(4, 'Fechas y estaciones', 'autumn/fall', 'otoño'),
(4, 'Fechas y estaciones', 'winter', 'invierno'),
(4, 'Fechas y estaciones', 'date', 'fecha'),
(4, 'Fechas y estaciones', 'birthday', 'cumpleaños'),
(4, 'Fechas y estaciones', 'calendar', 'calendario'),
(4, 'Fechas y estaciones', 'clock', 'reloj (de pared)'),
(4, 'Fechas y estaciones', 'watch', 'reloj (de pulsera)'),
(4, 'Fechas y estaciones', 'schedule', 'horario'),
(4, 'Fechas y estaciones', 'appointment', 'cita'),
(4, 'Fechas y estaciones', 'holiday', 'día festivo'),
(4, 'Fechas y estaciones', 'century', 'siglo'),
(4, 'Fechas y estaciones', 'now', 'ahora'),
(4, 'Fechas y estaciones', 'later', 'más tarde'),
(4, 'Fechas y estaciones', 'soon', 'pronto'),
(4, 'Fechas y estaciones', 'before', 'antes'),
(4, 'Fechas y estaciones', 'after', 'después'),
(4, 'Fechas y estaciones', 'during', 'durante'),
(4, 'Fechas y estaciones', 'next', 'próximo'),
(4, 'Fechas y estaciones', 'last', 'pasado/último'),
(4, 'Fechas y estaciones', 'ago', 'hace (tiempo)'),
(4, 'Fechas y estaciones', 'on time', 'puntual');
