-- SEMANA 16 · Planes, proyectos y objetivos · 70 palabras
insert into words (week, section, en, es) values
(16, 'Planes y decisiones', 'to plan', 'planear'),
(16, 'Planes y decisiones', 'project', 'proyecto'),
(16, 'Planes y decisiones', 'objective', 'objetivo'),
(16, 'Planes y decisiones', 'purpose', 'propósito'),
(16, 'Planes y decisiones', 'intention', 'intención'),
(16, 'Planes y decisiones', 'decision', 'decisión'),
(16, 'Planes y decisiones', 'to decide', 'decidir'),
(16, 'Planes y decisiones', 'to choose', 'elegir'),
(16, 'Planes y decisiones', 'choice', 'elección'),
(16, 'Planes y decisiones', 'option', 'opción'),
(16, 'Planes y decisiones', 'opportunity', 'oportunidad'),
(16, 'Planes y decisiones', 'chance', 'posibilidad/ocasión'),
(16, 'Planes y decisiones', 'future', 'futuro'),
(16, 'Planes y decisiones', 'next week', 'la próxima semana'),
(16, 'Planes y decisiones', 'next year', 'el año que viene'),
(16, 'Planes y decisiones', 'someday', 'algún día'),
(16, 'Planes y decisiones', 'to hope', 'esperar (desear)'),
(16, 'Planes y decisiones', 'hope', 'esperanza'),
(16, 'Planes y decisiones', 'to expect', 'esperar (prever)'),
(16, 'Planes y decisiones', 'to intend', 'tener la intención de'),
(16, 'Planes y decisiones', 'to prepare', 'preparar'),
(16, 'Planes y decisiones', 'preparation', 'preparación'),
(16, 'Planes y decisiones', 'step', 'paso'),
(16, 'Planes y decisiones', 'stage (phase)', 'etapa'),
(16, 'Organización y compromiso', 'list', 'lista'),
(16, 'Organización y compromiso', 'to make a list', 'hacer una lista'),
(16, 'Organización y compromiso', 'priority', 'prioridad'),
(16, 'Organización y compromiso', 'deadline', 'fecha límite'),
(16, 'Organización y compromiso', 'timetable', 'horario (tabla)'),
(16, 'Organización y compromiso', 'to postpone', 'posponer'),
(16, 'Organización y compromiso', 'to arrange', 'concertar/organizar'),
(16, 'Organización y compromiso', 'meeting', 'reunión'),
(16, 'Organización y compromiso', 'to attend', 'asistir'),
(16, 'Organización y compromiso', 'to confirm', 'confirmar'),
(16, 'Organización y compromiso', 'to promise', 'prometer'),
(16, 'Organización y compromiso', 'promise', 'promesa'),
(16, 'Organización y compromiso', 'to commit', 'comprometerse'),
(16, 'Organización y compromiso', 'commitment', 'compromiso'),
(16, 'Organización y compromiso', 'effort', 'esfuerzo'),
(16, 'Organización y compromiso', 'to try', 'intentar'),
(16, 'Organización y compromiso', 'to manage to', 'lograr/conseguir'),
(16, 'Organización y compromiso', 'to succeed', 'tener éxito'),
(16, 'Organización y compromiso', 'to fail', 'fracasar'),
(16, 'Organización y compromiso', 'possible', 'posible'),
(16, 'Organización y compromiso', 'impossible', 'imposible'),
(16, 'Organización y compromiso', 'likely', 'probable'),
(16, 'Organización y compromiso', 'unlikely', 'improbable'),
(16, 'Organización y compromiso', 'sure', 'seguro (convencido)'),
(16, 'Riesgo y motivación', 'doubt', 'duda'),
(16, 'Riesgo y motivación', 'to doubt', 'dudar'),
(16, 'Riesgo y motivación', 'risk', 'riesgo'),
(16, 'Riesgo y motivación', 'to risk', 'arriesgar'),
(16, 'Riesgo y motivación', 'advantage', 'ventaja'),
(16, 'Riesgo y motivación', 'disadvantage', 'desventaja'),
(16, 'Riesgo y motivación', 'to improve', 'mejorar'),
(16, 'Riesgo y motivación', 'improvement', 'mejora'),
(16, 'Riesgo y motivación', 'to give up', 'rendirse'),
(16, 'Riesgo y motivación', 'to keep on', 'continuar'),
(16, 'Riesgo y motivación', 'to start over', 'empezar de nuevo'),
(16, 'Riesgo y motivación', 'motivation', 'motivación'),
(16, 'Riesgo y motivación', 'motivated', 'motivado'),
(16, 'Riesgo y motivación', 'ambitious', 'ambicioso'),
(16, 'Riesgo y motivación', 'realistic', 'realista'),
(16, 'Riesgo y motivación', 'long-term', 'a largo plazo'),
(16, 'Riesgo y motivación', 'short-term', 'a corto plazo'),
(16, 'Riesgo y motivación', 'to save up', 'ahorrar para algo'),
(16, 'Riesgo y motivación', 'to move on', 'seguir adelante'),
(16, 'Riesgo y motivación', 'dream job', 'trabajo soñado'),
(16, 'Riesgo y motivación', 'to set a goal', 'fijar una meta'),
(16, 'Riesgo y motivación', 'to achieve a goal', 'alcanzar una meta');
