-- SEMANA 15 · Geografía, naturaleza y animales · 70 palabras
insert into words (week, section, en, es) values
(15, 'Geografía y paisaje', 'earth', 'tierra (planeta)'),
(15, 'Geografía y paisaje', 'continent', 'continente'),
(15, 'Geografía y paisaje', 'ocean', 'océano'),
(15, 'Geografía y paisaje', 'sea', 'mar'),
(15, 'Geografía y paisaje', 'lake', 'lago'),
(15, 'Geografía y paisaje', 'waterfall', 'cascada'),
(15, 'Geografía y paisaje', 'coast', 'costa'),
(15, 'Geografía y paisaje', 'island', 'isla'),
(15, 'Geografía y paisaje', 'desert', 'desierto'),
(15, 'Geografía y paisaje', 'forest', 'bosque'),
(15, 'Geografía y paisaje', 'jungle', 'selva'),
(15, 'Geografía y paisaje', 'hill', 'colina'),
(15, 'Geografía y paisaje', 'valley', 'valle'),
(15, 'Geografía y paisaje', 'volcano', 'volcán'),
(15, 'Geografía y paisaje', 'cave', 'cueva'),
(15, 'Geografía y paisaje', 'rock', 'roca'),
(15, 'Geografía y paisaje', 'stone', 'piedra'),
(15, 'Geografía y paisaje', 'sand', 'arena'),
(15, 'Geografía y paisaje', 'soil', 'suelo/tierra'),
(15, 'Geografía y paisaje', 'grass', 'hierba'),
(15, 'Geografía y paisaje', 'tree', 'árbol'),
(15, 'Geografía y paisaje', 'leaf', 'hoja'),
(15, 'Geografía y paisaje', 'flower', 'flor'),
(15, 'Geografía y paisaje', 'branch', 'rama'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'root', 'raíz'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'seed', 'semilla'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'sky', 'cielo'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'star', 'estrella'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'moon', 'luna'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'sun', 'sol'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'planet', 'planeta'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'north', 'norte'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'south', 'sur'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'east', 'este'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'west', 'oeste'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'animal', 'animal'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'dog', 'perro'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'cat', 'gato'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'bird', 'pájaro'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'horse', 'caballo'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'cow', 'vaca'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'pig', 'cerdo (animal)'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'sheep', 'oveja'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'goat', 'cabra'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'rabbit', 'conejo'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'mouse', 'ratón'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'bear', 'oso'),
(15, 'Cielo, puntos cardinales y animales domésticos', 'wolf', 'lobo'),
(15, 'Animales salvajes y del campo', 'lion', 'león'),
(15, 'Animales salvajes y del campo', 'tiger', 'tigre'),
(15, 'Animales salvajes y del campo', 'elephant', 'elefante'),
(15, 'Animales salvajes y del campo', 'monkey', 'mono'),
(15, 'Animales salvajes y del campo', 'giraffe', 'jirafa'),
(15, 'Animales salvajes y del campo', 'snake', 'serpiente'),
(15, 'Animales salvajes y del campo', 'spider', 'araña'),
(15, 'Animales salvajes y del campo', 'insect', 'insecto'),
(15, 'Animales salvajes y del campo', 'bee', 'abeja'),
(15, 'Animales salvajes y del campo', 'butterfly', 'mariposa'),
(15, 'Animales salvajes y del campo', 'whale', 'ballena'),
(15, 'Animales salvajes y del campo', 'dolphin', 'delfín'),
(15, 'Animales salvajes y del campo', 'shark', 'tiburón'),
(15, 'Animales salvajes y del campo', 'turtle', 'tortuga'),
(15, 'Animales salvajes y del campo', 'frog', 'rana'),
(15, 'Animales salvajes y del campo', 'duck', 'pato'),
(15, 'Animales salvajes y del campo', 'hen', 'gallina'),
(15, 'Animales salvajes y del campo', 'wild', 'salvaje'),
(15, 'Animales salvajes y del campo', 'pet', 'mascota'),
(15, 'Animales salvajes y del campo', 'farm', 'granja'),
(15, 'Animales salvajes y del campo', 'nature', 'naturaleza'),
(15, 'Animales salvajes y del campo', 'landscape', 'paisaje');
