-- SEMANA 28 · Comunicación, medios y opiniones · 71 palabras
insert into words (week, section, en, es) values
(28, 'Medios de comunicación', 'communication', 'comunicación'),
(28, 'Medios de comunicación', 'to communicate', 'comunicarse'),
(28, 'Medios de comunicación', 'the media', 'los medios de comunicación'),
(28, 'Medios de comunicación', 'newspaper', 'periódico'),
(28, 'Medios de comunicación', 'magazine', 'revista'),
(28, 'Medios de comunicación', 'article', 'artículo'),
(28, 'Medios de comunicación', 'headline', 'titular'),
(28, 'Medios de comunicación', 'reporter', 'reportero'),
(28, 'Medios de comunicación', 'the press', 'la prensa'),
(28, 'Medios de comunicación', 'radio', 'radio'),
(28, 'Medios de comunicación', 'channel', 'canal'),
(28, 'Medios de comunicación', 'TV program', 'programa de TV'),
(28, 'Medios de comunicación', 'broadcast', 'emisión'),
(28, 'Medios de comunicación', 'to broadcast', 'emitir'),
(28, 'Medios de comunicación', 'live', 'en directo'),
(28, 'Medios de comunicación', 'viewer', 'espectador'),
(28, 'Medios de comunicación', 'audience', 'audiencia/público'),
(28, 'Medios de comunicación', 'advertisement', 'anuncio (publicidad)'),
(28, 'Medios de comunicación', 'to advertise', 'anunciar (publicidad)'),
(28, 'Medios de comunicación', 'advertising', 'publicidad'),
(28, 'Medios de comunicación', 'commercial', 'anuncio de TV'),
(28, 'Medios de comunicación', 'blog', 'blog'),
(28, 'Medios de comunicación', 'blogger', 'bloguero'),
(28, 'Medios de comunicación', 'podcast', 'pódcast'),
(28, 'Opinión y debate', 'influencer', 'influencer'),
(28, 'Opinión y debate', 'content', 'contenido'),
(28, 'Opinión y debate', 'information', 'información'),
(28, 'Opinión y debate', 'source', 'fuente'),
(28, 'Opinión y debate', 'fact', 'hecho'),
(28, 'Opinión y debate', 'opinion', 'opinión'),
(28, 'Opinión y debate', 'in my opinion', 'en mi opinión'),
(28, 'Opinión y debate', 'point of view', 'punto de vista'),
(28, 'Opinión y debate', 'to express', 'expresar'),
(28, 'Opinión y debate', 'to state', 'afirmar'),
(28, 'Opinión y debate', 'statement', 'declaración'),
(28, 'Opinión y debate', 'to claim', 'sostener/afirmar'),
(28, 'Opinión y debate', 'to argue', 'argumentar/discutir'),
(28, 'Opinión y debate', 'argument', 'argumento/discusión'),
(28, 'Opinión y debate', 'debate', 'debate'),
(28, 'Opinión y debate', 'to debate', 'debatir'),
(28, 'Opinión y debate', 'discussion', 'conversación/debate'),
(28, 'Opinión y debate', 'to discuss', 'hablar de/debatir'),
(28, 'Opinión y debate', 'to convince', 'convencer'),
(28, 'Opinión y debate', 'to persuade', 'persuadir'),
(28, 'Opinión y debate', 'to influence', 'influir'),
(28, 'Opinión y debate', 'to inform', 'informar'),
(28, 'Opinión y debate', 'to comment', 'comentar'),
(28, 'Opinión y debate', 'comment', 'comentario'),
(28, 'Confianza y crítica', 'criticism', 'crítica'),
(28, 'Confianza y crítica', 'to criticize', 'criticar'),
(28, 'Confianza y crítica', 'critic', 'crítico (persona)'),
(28, 'Confianza y crítica', 'to praise', 'elogiar'),
(28, 'Confianza y crítica', 'to complain', 'quejarse'),
(28, 'Confianza y crítica', 'complaint', 'queja'),
(28, 'Confianza y crítica', 'to protest', 'protestar'),
(28, 'Confianza y crítica', 'freedom of speech', 'libertad de expresión'),
(28, 'Confianza y crítica', 'fake news', 'noticias falsas'),
(28, 'Confianza y crítica', 'to trust', 'confiar'),
(28, 'Confianza y crítica', 'reliable', 'fiable'),
(28, 'Confianza y crítica', 'unreliable', 'poco fiable'),
(28, 'Confianza y crítica', 'honest', 'honesto'),
(28, 'Confianza y crítica', 'dishonest', 'deshonesto'),
(28, 'Confianza y crítica', 'to exaggerate', 'exagerar'),
(28, 'Confianza y crítica', 'to summarize', 'resumir'),
(28, 'Confianza y crítica', 'summary', 'resumen'),
(28, 'Confianza y crítica', 'to translate', 'traducir'),
(28, 'Confianza y crítica', 'translation', 'traducción'),
(28, 'Confianza y crítica', 'meaning', 'significado'),
(28, 'Confianza y crítica', 'to mean', 'significar'),
(28, 'Confianza y crítica', 'to understand', 'entender'),
(28, 'Confianza y crítica', 'misunderstanding', 'malentendido');
