-- SEMANA 14 · Compras, dinero y precios · 70 palabras
insert into words (week, section, en, es) values
(14, 'Compras y precios', 'shopping', 'compras'),
(14, 'Compras y precios', 'customer', 'cliente'),
(14, 'Compras y precios', 'shop assistant', 'dependiente'),
(14, 'Compras y precios', 'cashier', 'cajero (persona)'),
(14, 'Compras y precios', 'price', 'precio'),
(14, 'Compras y precios', 'cheap', 'barato'),
(14, 'Compras y precios', 'expensive', 'caro'),
(14, 'Compras y precios', 'to cost', 'costar'),
(14, 'Compras y precios', 'money', 'dinero'),
(14, 'Compras y precios', 'cash', 'efectivo'),
(14, 'Compras y precios', 'coin', 'moneda (pieza)'),
(14, 'Compras y precios', 'banknote', 'billete (dinero)'),
(14, 'Compras y precios', 'credit card', 'tarjeta de crédito'),
(14, 'Compras y precios', 'debit card', 'tarjeta de débito'),
(14, 'Compras y precios', 'to pay', 'pagar'),
(14, 'Compras y precios', 'payment', 'pago'),
(14, 'Compras y precios', 'change (money)', 'cambio/vuelto'),
(14, 'Compras y precios', 'receipt', 'recibo'),
(14, 'Compras y precios', 'discount', 'descuento'),
(14, 'Compras y precios', 'sale', 'rebajas'),
(14, 'Compras y precios', 'offer', 'oferta'),
(14, 'Compras y precios', 'bargain', 'ganga'),
(14, 'Compras y precios', 'free', 'gratis'),
(14, 'Compras y precios', 'to spend', 'gastar'),
(14, 'Dinero y banco', 'to save', 'ahorrar'),
(14, 'Dinero y banco', 'savings', 'ahorros'),
(14, 'Dinero y banco', 'to borrow', 'pedir prestado'),
(14, 'Dinero y banco', 'to lend', 'prestar'),
(14, 'Dinero y banco', 'to owe', 'deber (dinero)'),
(14, 'Dinero y banco', 'debt', 'deuda'),
(14, 'Dinero y banco', 'loan', 'préstamo'),
(14, 'Dinero y banco', 'bank account', 'cuenta bancaria'),
(14, 'Dinero y banco', 'cash machine/ATM', 'cajero automático'),
(14, 'Dinero y banco', 'to withdraw', 'retirar (dinero)'),
(14, 'Dinero y banco', 'salary', 'salario'),
(14, 'Dinero y banco', 'to earn', 'ganar (dinero)'),
(14, 'Dinero y banco', 'rich', 'rico'),
(14, 'Dinero y banco', 'poor', 'pobre'),
(14, 'Dinero y banco', 'to afford', 'poder permitirse'),
(14, 'Dinero y banco', 'quality', 'calidad'),
(14, 'Dinero y banco', 'brand', 'marca'),
(14, 'Dinero y banco', 'product', 'producto'),
(14, 'Dinero y banco', 'item', 'artículo'),
(14, 'Dinero y banco', 'basket', 'cesta'),
(14, 'Dinero y banco', 'cart/trolley', 'carrito'),
(14, 'Dinero y banco', 'queue/line', 'fila'),
(14, 'Dinero y banco', 'to queue', 'hacer fila'),
(14, 'Dinero y banco', 'shop window', 'escaparate'),
(14, 'Devoluciones y compras online', 'to return (an item)', 'devolver'),
(14, 'Devoluciones y compras online', 'refund', 'reembolso'),
(14, 'Devoluciones y compras online', 'to exchange (an item)', 'cambiar (un artículo)'),
(14, 'Devoluciones y compras online', 'warranty', 'garantía'),
(14, 'Devoluciones y compras online', 'wallet', 'cartera'),
(14, 'Devoluciones y compras online', 'purse', 'monedero'),
(14, 'Devoluciones y compras online', 'bag', 'bolsa'),
(14, 'Devoluciones y compras online', 'plastic bag', 'bolsa de plástico'),
(14, 'Devoluciones y compras online', 'gift card', 'tarjeta regalo'),
(14, 'Devoluciones y compras online', 'online shopping', 'compras por internet'),
(14, 'Devoluciones y compras online', 'delivery', 'entrega'),
(14, 'Devoluciones y compras online', 'to deliver', 'entregar'),
(14, 'Devoluciones y compras online', 'order (purchase)', 'pedido'),
(14, 'Devoluciones y compras online', 'worth it', 'vale la pena'),
(14, 'Devoluciones y compras online', 'tax', 'impuesto'),
(14, 'Devoluciones y compras online', 'bill (invoice)', 'factura'),
(14, 'Devoluciones y compras online', 'budget', 'presupuesto'),
(14, 'Devoluciones y compras online', 'to compare', 'comparar'),
(14, 'Devoluciones y compras online', 'similar', 'similar'),
(14, 'Devoluciones y compras online', 'different', 'diferente'),
(14, 'Devoluciones y compras online', 'the same', 'igual'),
(14, 'Devoluciones y compras online', 'cost', 'costo');
