-- SEMANA 30 · Conectores y expresiones B1 (repaso final) · 68 palabras
-- Nota: el título original decía "70 palabras"; transcribiendo la tabla con cuidado
-- solo conté 68. Si tienes el listado en texto plano, dime y reviso las que falten.
insert into words (week, section, en, es) values
(30, 'Contraste y causa', 'although', 'aunque'),
(30, 'Contraste y causa', 'even though', 'aunque (enfático)'),
(30, 'Contraste y causa', 'despite', 'a pesar de'),
(30, 'Contraste y causa', 'in spite of', 'a pesar de (sinónimo)'),
(30, 'Contraste y causa', 'whereas', 'mientras que'),
(30, 'Contraste y causa', 'on the other hand', 'por otro lado'),
(30, 'Contraste y causa', 'on the one hand', 'por un lado'),
(30, 'Contraste y causa', 'in addition', 'además'),
(30, 'Contraste y causa', 'besides', 'además (aparte)'),
(30, 'Contraste y causa', 'moreover', 'además (formal)'),
(30, 'Contraste y causa', 'furthermore', 'es más'),
(30, 'Contraste y causa', 'as well as', 'así como'),
(30, 'Contraste y causa', 'not only... but also', 'no solo... sino también'),
(30, 'Contraste y causa', 'therefore', 'por lo tanto'),
(30, 'Contraste y causa', 'as a result', 'como resultado'),
(30, 'Contraste y causa', 'consequently', 'en consecuencia'),
(30, 'Contraste y causa', 'that''s why', 'por eso'),
(30, 'Contraste y causa', 'since (because)', 'ya que'),
(30, 'Contraste y causa', 'due to', 'debido a'),
(30, 'Contraste y causa', 'because of', 'a causa de'),
(30, 'Contraste y causa', 'thanks to', 'gracias a'),
(30, 'Contraste y causa', 'in order to', 'para (finalidad)'),
(30, 'Contraste y causa', 'so that', 'para que'),
(30, 'Contraste y causa', 'such as', 'como (por ejemplo)'),
(30, 'Precisión y estructura', 'in other words', 'en otras palabras'),
(30, 'Precisión y estructura', 'that is to say', 'es decir'),
(30, 'Precisión y estructura', 'in general', 'en general'),
(30, 'Precisión y estructura', 'generally', 'generalmente'),
(30, 'Precisión y estructura', 'in particular', 'en particular'),
(30, 'Precisión y estructura', 'especially', 'especialmente'),
(30, 'Precisión y estructura', 'mainly', 'principalmente'),
(30, 'Precisión y estructura', 'mostly', 'mayormente'),
(30, 'Precisión y estructura', 'according to', 'según'),
(30, 'Precisión y estructura', 'as for', 'en cuanto a'),
(30, 'Precisión y estructura', 'regarding', 'con respecto a'),
(30, 'Precisión y estructura', 'in terms of', 'en términos de'),
(30, 'Precisión y estructura', 'to sum up', 'en resumen'),
(30, 'Precisión y estructura', 'in conclusion', 'en conclusión'),
(30, 'Precisión y estructura', 'in short', 'en pocas palabras'),
(30, 'Precisión y estructura', 'all in all', 'en definitiva'),
(30, 'Precisión y estructura', 'firstly', 'en primer lugar'),
(30, 'Precisión y estructura', 'secondly', 'en segundo lugar'),
(30, 'Precisión y estructura', 'lastly', 'por último'),
(30, 'Precisión y estructura', 'afterwards', 'después/posteriormente'),
(30, 'Precisión y estructura', 'eventually', 'finalmente (con el tiempo)'),
(30, 'Precisión y estructura', 'as soon as', 'tan pronto como'),
(30, 'Expresiones finales B1', 'whenever', 'cuando sea/siempre que'),
(30, 'Expresiones finales B1', 'wherever', 'donde sea'),
(30, 'Expresiones finales B1', 'whoever', 'quien sea'),
(30, 'Expresiones finales B1', 'whatever', 'lo que sea'),
(30, 'Expresiones finales B1', 'anyway', 'de todos modos'),
(30, 'Expresiones finales B1', 'indeed', 'de hecho (enfático)'),
(30, 'Expresiones finales B1', 'obviously', 'obviamente'),
(30, 'Expresiones finales B1', 'clearly', 'claramente'),
(30, 'Expresiones finales B1', 'definitely', 'definitivamente'),
(30, 'Expresiones finales B1', 'certainly', 'ciertamente'),
(30, 'Expresiones finales B1', 'probably', 'probablemente'),
(30, 'Expresiones finales B1', 'surprisingly', 'sorprendentemente'),
(30, 'Expresiones finales B1', 'honestly', 'sinceramente'),
(30, 'Expresiones finales B1', 'to be honest', 'para ser sincero'),
(30, 'Expresiones finales B1', 'hopefully', 'con suerte/ojalá'),
(30, 'Expresiones finales B1', 'it depends', 'depende'),
(30, 'Expresiones finales B1', 'it seems that', 'parece que'),
(30, 'Expresiones finales B1', 'as long as', 'siempre y cuando'),
(30, 'Expresiones finales B1', 'even if', 'incluso si'),
(30, 'Expresiones finales B1', 'in my view', 'a mi modo de ver'),
(30, 'Expresiones finales B1', 'no matter what', 'pase lo que pase'),
(30, 'Expresiones finales B1', 'at the end of the day', 'al fin y al cabo');
