-- SEMANA 5 · Casa, muebles y habitaciones · 61 palabras
insert into words (week, section, en, es) values
(5, 'La casa y las habitaciones', 'house', 'casa'),
(5, 'La casa y las habitaciones', 'apartment/flat', 'apartamento'),
(5, 'La casa y las habitaciones', 'home', 'hogar'),
(5, 'La casa y las habitaciones', 'room', 'habitación'),
(5, 'La casa y las habitaciones', 'living room', 'sala de estar'),
(5, 'La casa y las habitaciones', 'bedroom', 'dormitorio'),
(5, 'La casa y las habitaciones', 'kitchen', 'cocina'),
(5, 'La casa y las habitaciones', 'bathroom', 'baño'),
(5, 'La casa y las habitaciones', 'dining room', 'comedor'),
(5, 'La casa y las habitaciones', 'garage', 'garaje'),
(5, 'La casa y las habitaciones', 'garden', 'jardín'),
(5, 'La casa y las habitaciones', 'balcony', 'balcón'),
(5, 'La casa y las habitaciones', 'stairs', 'escaleras'),
(5, 'La casa y las habitaciones', 'floor', 'piso/suelo'),
(5, 'La casa y las habitaciones', 'wall', 'pared'),
(5, 'La casa y las habitaciones', 'ceiling', 'techo (interior)'),
(5, 'La casa y las habitaciones', 'roof', 'tejado'),
(5, 'La casa y las habitaciones', 'door', 'puerta'),
(5, 'La casa y las habitaciones', 'window', 'ventana'),
(5, 'La casa y las habitaciones', 'key', 'llave'),
(5, 'La casa y las habitaciones', 'furniture', 'muebles'),
(5, 'Muebles y objetos', 'table', 'mesa'),
(5, 'Muebles y objetos', 'chair', 'silla'),
(5, 'Muebles y objetos', 'sofa', 'sofá'),
(5, 'Muebles y objetos', 'armchair', 'sillón'),
(5, 'Muebles y objetos', 'bed', 'cama'),
(5, 'Muebles y objetos', 'wardrobe', 'armario (ropa)'),
(5, 'Muebles y objetos', 'shelf', 'estante'),
(5, 'Muebles y objetos', 'desk', 'escritorio'),
(5, 'Muebles y objetos', 'lamp', 'lámpara'),
(5, 'Muebles y objetos', 'light', 'luz'),
(5, 'Muebles y objetos', 'mirror', 'espejo'),
(5, 'Muebles y objetos', 'carpet', 'alfombra'),
(5, 'Muebles y objetos', 'curtain', 'cortina'),
(5, 'Muebles y objetos', 'picture', 'cuadro'),
(5, 'Muebles y objetos', 'television', 'televisión'),
(5, 'Muebles y objetos', 'fridge', 'nevera'),
(5, 'Muebles y objetos', 'oven', 'horno'),
(5, 'Muebles y objetos', 'microwave', 'microondas'),
(5, 'Muebles y objetos', 'washing machine', 'lavadora'),
(5, 'Muebles y objetos', 'dishwasher', 'lavavajillas'),
(5, 'Muebles y objetos', 'sink', 'fregadero'),
(5, 'Baño, alquiler y alrededores', 'shower', 'ducha'),
(5, 'Baño, alquiler y alrededores', 'bathtub', 'bañera'),
(5, 'Baño, alquiler y alrededores', 'toilet', 'inodoro'),
(5, 'Baño, alquiler y alrededores', 'towel', 'toalla'),
(5, 'Baño, alquiler y alrededores', 'pillow', 'almohada'),
(5, 'Baño, alquiler y alrededores', 'blanket', 'manta'),
(5, 'Baño, alquiler y alrededores', 'sheet', 'sábana'),
(5, 'Baño, alquiler y alrededores', 'cupboard', 'alacena'),
(5, 'Baño, alquiler y alrededores', 'drawer', 'cajón'),
(5, 'Baño, alquiler y alrededores', 'plant', 'planta'),
(5, 'Baño, alquiler y alrededores', 'neighbor', 'vecino'),
(5, 'Baño, alquiler y alrededores', 'neighborhood', 'barrio'),
(5, 'Baño, alquiler y alrededores', 'to rent', 'alquilar'),
(5, 'Baño, alquiler y alrededores', 'rent', 'alquiler (dinero)'),
(5, 'Baño, alquiler y alrededores', 'to move (house)', 'mudarse'),
(5, 'Baño, alquiler y alrededores', 'upstairs', 'arriba (piso)'),
(5, 'Baño, alquiler y alrededores', 'downstairs', 'abajo (piso)'),
(5, 'Baño, alquiler y alrededores', 'comfortable', 'cómodo'),
(5, 'Baño, alquiler y alrededores', 'cozy', 'acogedor');
