-- SEMANA 27 · Inventos, procesos y materiales · 76 palabras
insert into words (week, section, en, es) values
(27, 'Inventar y fabricar', 'inventor', 'inventor'),
(27, 'Inventar y fabricar', 'to create', 'crear'),
(27, 'Inventar y fabricar', 'creation', 'creación'),
(27, 'Inventar y fabricar', 'creative', 'creativo'),
(27, 'Inventar y fabricar', 'to design', 'diseñar'),
(27, 'Inventar y fabricar', 'design', 'diseño'),
(27, 'Inventar y fabricar', 'to develop', 'desarrollar'),
(27, 'Inventar y fabricar', 'development', 'desarrollo'),
(27, 'Inventar y fabricar', 'to produce', 'producir'),
(27, 'Inventar y fabricar', 'production', 'producción'),
(27, 'Inventar y fabricar', 'to manufacture', 'fabricar'),
(27, 'Inventar y fabricar', 'machine', 'máquina'),
(27, 'Inventar y fabricar', 'machinery', 'maquinaria'),
(27, 'Inventar y fabricar', 'engine', 'motor'),
(27, 'Inventar y fabricar', 'tool', 'herramienta'),
(27, 'Inventar y fabricar', 'equipment', 'equipo (material)'),
(27, 'Inventar y fabricar', 'material', 'material'),
(27, 'Inventar y fabricar', 'wood', 'madera'),
(27, 'Inventar y fabricar', 'wooden', 'de madera'),
(27, 'Inventar y fabricar', 'steel', 'acero'),
(27, 'Inventar y fabricar', 'iron', 'hierro'),
(27, 'Inventar y fabricar', 'gold', 'oro'),
(27, 'Inventar y fabricar', 'silver', 'plata'),
(27, 'Inventar y fabricar', 'copper', 'cobre'),
(27, 'Inventar y fabricar', 'rubber', 'goma/caucho'),
(27, 'Inventar y fabricar', 'leather', 'cuero'),
(27, 'Materiales y construcción', 'cotton', 'algodón'),
(27, 'Materiales y construcción', 'wool', 'lana'),
(27, 'Materiales y construcción', 'silk', 'seda'),
(27, 'Materiales y construcción', 'fabric', 'tela'),
(27, 'Materiales y construcción', 'brick', 'ladrillo'),
(27, 'Materiales y construcción', 'cement', 'cemento'),
(27, 'Materiales y construcción', 'concrete', 'hormigón'),
(27, 'Materiales y construcción', 'clay', 'arcilla'),
(27, 'Materiales y construcción', 'to build', 'construir'),
(27, 'Materiales y construcción', 'construction', 'construcción'),
(27, 'Materiales y construcción', 'to assemble', 'montar/ensamblar'),
(27, 'Materiales y construcción', 'to be made of', 'estar hecho de'),
(27, 'Materiales y construcción', 'to consist of', 'consistir en'),
(27, 'Materiales y construcción', 'process', 'proceso'),
(27, 'Materiales y construcción', 'method', 'método'),
(27, 'Materiales y construcción', 'technique', 'técnica'),
(27, 'Materiales y construcción', 'system', 'sistema'),
(27, 'Materiales y construcción', 'to work (function)', 'funcionar'),
(27, 'Materiales y construcción', 'function', 'función'),
(27, 'Materiales y construcción', 'to operate', 'operar/manejar'),
(27, 'Materiales y construcción', 'instructions', 'instrucciones'),
(27, 'Materiales y construcción', 'manual', 'manual (libro)'),
(27, 'Materiales y construcción', 'patent', 'patente'),
(27, 'Materiales y construcción', 'experiment', 'experimento'),
(27, 'Materiales y construcción', 'laboratory', 'laboratorio'),
(27, 'Materiales y construcción', 'research', 'investigación'),
(27, 'Investigación y medidas', 'to research', 'investigar'),
(27, 'Investigación y medidas', 'researcher', 'investigador'),
(27, 'Investigación y medidas', 'science', 'ciencia'),
(27, 'Investigación y medidas', 'scientific', 'científico (adj)'),
(27, 'Investigación y medidas', 'to test', 'probar (testear)'),
(27, 'Investigación y medidas', 'sample', 'muestra'),
(27, 'Investigación y medidas', 'to measure', 'medir'),
(27, 'Investigación y medidas', 'measurement', 'medida'),
(27, 'Investigación y medidas', 'weight', 'peso'),
(27, 'Investigación y medidas', 'to weigh', 'pesar'),
(27, 'Investigación y medidas', 'length', 'longitud'),
(27, 'Investigación y medidas', 'width', 'anchura'),
(27, 'Investigación y medidas', 'height', 'altura'),
(27, 'Investigación y medidas', 'shape', 'forma'),
(27, 'Investigación y medidas', 'round', 'redondo'),
(27, 'Investigación y medidas', 'flat', 'plano'),
(27, 'Investigación y medidas', 'heavy', 'pesado'),
(27, 'Investigación y medidas', 'light (weight)', 'ligero'),
(27, 'Investigación y medidas', 'hard', 'duro'),
(27, 'Investigación y medidas', 'soft', 'blando'),
(27, 'Investigación y medidas', 'smooth', 'suave'),
(27, 'Investigación y medidas', 'rough', 'áspero'),
(27, 'Investigación y medidas', 'strong', 'fuerte'),
(27, 'Investigación y medidas', 'weak', 'débil');
