-- SEMANA 7 · Ropa y el tiempo (clima) · 60 palabras
insert into words (week, section, en, es) values
(7, 'Ropa', 'clothes', 'ropa'),
(7, 'Ropa', 'shirt', 'camisa'),
(7, 'Ropa', 't-shirt', 'camiseta'),
(7, 'Ropa', 'trousers/pants', 'pantalones'),
(7, 'Ropa', 'jeans', 'vaqueros'),
(7, 'Ropa', 'skirt', 'falda'),
(7, 'Ropa', 'dress', 'vestido'),
(7, 'Ropa', 'suit', 'traje'),
(7, 'Ropa', 'jacket', 'chaqueta'),
(7, 'Ropa', 'coat', 'abrigo'),
(7, 'Ropa', 'sweater', 'suéter'),
(7, 'Ropa', 'hoodie', 'sudadera'),
(7, 'Ropa', 'shorts', 'pantalones cortos'),
(7, 'Ropa', 'socks', 'calcetines'),
(7, 'Ropa', 'shoes', 'zapatos'),
(7, 'Ropa', 'boots', 'botas'),
(7, 'Ropa', 'sneakers/trainers', 'zapatillas'),
(7, 'Ropa', 'sandals', 'sandalias'),
(7, 'Ropa', 'hat', 'sombrero'),
(7, 'Ropa', 'cap', 'gorra'),
(7, 'Accesorios y cómo queda la ropa', 'scarf', 'bufanda'),
(7, 'Accesorios y cómo queda la ropa', 'gloves', 'guantes'),
(7, 'Accesorios y cómo queda la ropa', 'belt', 'cinturón'),
(7, 'Accesorios y cómo queda la ropa', 'tie', 'corbata'),
(7, 'Accesorios y cómo queda la ropa', 'underwear', 'ropa interior'),
(7, 'Accesorios y cómo queda la ropa', 'pajamas', 'pijama'),
(7, 'Accesorios y cómo queda la ropa', 'swimsuit', 'bañador'),
(7, 'Accesorios y cómo queda la ropa', 'pocket', 'bolsillo'),
(7, 'Accesorios y cómo queda la ropa', 'button', 'botón'),
(7, 'Accesorios y cómo queda la ropa', 'zipper', 'cremallera'),
(7, 'Accesorios y cómo queda la ropa', 'size', 'talla'),
(7, 'Accesorios y cómo queda la ropa', 'to wear', 'llevar puesto'),
(7, 'Accesorios y cómo queda la ropa', 'to put on', 'ponerse'),
(7, 'Accesorios y cómo queda la ropa', 'to take off', 'quitarse'),
(7, 'Accesorios y cómo queda la ropa', 'to try on', 'probarse'),
(7, 'Accesorios y cómo queda la ropa', 'to fit', 'quedar bien (talla)'),
(7, 'Accesorios y cómo queda la ropa', 'fashion', 'moda'),
(7, 'Accesorios y cómo queda la ropa', 'style', 'estilo'),
(7, 'Accesorios y cómo queda la ropa', 'weather', 'tiempo (clima)'),
(7, 'Accesorios y cómo queda la ropa', 'sunny', 'soleado'),
(7, 'El clima', 'cloudy', 'nublado'),
(7, 'El clima', 'rainy', 'lluvioso'),
(7, 'El clima', 'rain', 'lluvia'),
(7, 'El clima', 'to rain', 'llover'),
(7, 'El clima', 'snow', 'nieve'),
(7, 'El clima', 'to snow', 'nevar'),
(7, 'El clima', 'wind', 'viento'),
(7, 'El clima', 'windy', 'ventoso'),
(7, 'El clima', 'storm', 'tormenta'),
(7, 'El clima', 'fog', 'niebla'),
(7, 'El clima', 'hot', 'caluroso'),
(7, 'El clima', 'warm', 'templado'),
(7, 'El clima', 'cold', 'frío'),
(7, 'El clima', 'cool', 'fresco'),
(7, 'El clima', 'dry', 'seco'),
(7, 'El clima', 'wet', 'mojado'),
(7, 'El clima', 'umbrella', 'paraguas'),
(7, 'El clima', 'temperature', 'temperatura'),
(7, 'El clima', 'degree', 'grado'),
(7, 'El clima', 'forecast', 'pronóstico');
