-- SEMANA 1 · Saludos, presentaciones y países · 62 palabras
-- Pega esto en el SQL Editor de Supabase DESPUES de haber corrido schema.sql

insert into words (week, section, en, es) values
(1, 'Saludos y despedidas', 'hello', 'hola'),
(1, 'Saludos y despedidas', 'hi', 'hola (informal)'),
(1, 'Saludos y despedidas', 'good morning', 'buenos días'),
(1, 'Saludos y despedidas', 'good afternoon', 'buenas tardes'),
(1, 'Saludos y despedidas', 'good evening', 'buenas noches (saludo)'),
(1, 'Saludos y despedidas', 'good night', 'buenas noches (despedida)'),
(1, 'Saludos y despedidas', 'goodbye', 'adiós'),
(1, 'Saludos y despedidas', 'bye', 'chao'),
(1, 'Saludos y despedidas', 'see you later', 'hasta luego'),
(1, 'Saludos y despedidas', 'see you soon', 'hasta pronto'),
(1, 'Saludos y despedidas', 'welcome', 'bienvenido'),
(1, 'Saludos y despedidas', 'please', 'por favor'),
(1, 'Saludos y despedidas', 'thank you', 'gracias'),
(1, 'Saludos y despedidas', 'thanks', 'gracias (informal)'),
(1, 'Saludos y despedidas', 'you''re welcome', 'de nada'),
(1, 'Saludos y despedidas', 'excuse me', 'disculpe'),
(1, 'Saludos y despedidas', 'sorry', 'lo siento'),
(1, 'Saludos y despedidas', 'yes', 'sí'),
(1, 'Saludos y despedidas', 'no', 'no'),
(1, 'Saludos y despedidas', 'name', 'nombre'),
(1, 'Saludos y despedidas', 'surname', 'apellido'),
(1, 'Presentaciones', 'first name', 'nombre de pila'),
(1, 'Presentaciones', 'age', 'edad'),
(1, 'Presentaciones', 'country', 'país'),
(1, 'Presentaciones', 'city', 'ciudad'),
(1, 'Presentaciones', 'nationality', 'nacionalidad'),
(1, 'Presentaciones', 'language', 'idioma'),
(1, 'Presentaciones', 'to meet', 'conocer (a alguien)'),
(1, 'Presentaciones', 'nice to meet you', 'encantado de conocerte'),
(1, 'Presentaciones', 'how are you?', '¿cómo estás?'),
(1, 'Presentaciones', 'fine', 'bien'),
(1, 'Presentaciones', 'to introduce', 'presentar'),
(1, 'Presentaciones', 'to speak', 'hablar'),
(1, 'Presentaciones', 'to live', 'vivir'),
(1, 'Presentaciones', 'to be from', 'ser de'),
(1, 'Presentaciones', 'address', 'dirección'),
(1, 'Presentaciones', 'phone number', 'número de teléfono'),
(1, 'Presentaciones', 'email', 'correo electrónico'),
(1, 'Presentaciones', 'to spell', 'deletrear'),
(1, 'Presentaciones', 'question', 'pregunta'),
(1, 'Presentaciones', 'answer', 'respuesta'),
(1, 'Países e idiomas', 'Spain', 'España'),
(1, 'Países e idiomas', 'Colombia', 'Colombia'),
(1, 'Países e idiomas', 'the United States', 'Estados Unidos'),
(1, 'Países e idiomas', 'England', 'Inglaterra'),
(1, 'Países e idiomas', 'France', 'Francia'),
(1, 'Países e idiomas', 'Germany', 'Alemania'),
(1, 'Países e idiomas', 'Italy', 'Italia'),
(1, 'Países e idiomas', 'Brazil', 'Brasil'),
(1, 'Países e idiomas', 'China', 'China'),
(1, 'Países e idiomas', 'Japan', 'Japón'),
(1, 'Países e idiomas', 'Mexico', 'México'),
(1, 'Países e idiomas', 'Spanish', 'español'),
(1, 'Países e idiomas', 'English', 'inglés'),
(1, 'Países e idiomas', 'French', 'francés'),
(1, 'Países e idiomas', 'German', 'alemán'),
(1, 'Personas', 'teacher', 'profesor'),
(1, 'Personas', 'student', 'estudiante'),
(1, 'Personas', 'friend', 'amigo'),
(1, 'Personas', 'person', 'persona'),
(1, 'Personas', 'people', 'gente'),
(1, 'Personas', 'world', 'mundo');
