-- SEMANA 12 · Etapas de la vida y biografías · 60 palabras
insert into words (week, section, en, es) values
(12, 'Infancia y juventud', 'life', 'vida'),
(12, 'Infancia y juventud', 'to be born', 'nacer'),
(12, 'Infancia y juventud', 'birth', 'nacimiento'),
(12, 'Infancia y juventud', 'childhood', 'infancia'),
(12, 'Infancia y juventud', 'kid', 'niño (informal)'),
(12, 'Infancia y juventud', 'teenager', 'adolescente'),
(12, 'Infancia y juventud', 'adult', 'adulto'),
(12, 'Infancia y juventud', 'youth', 'juventud'),
(12, 'Infancia y juventud', 'to grow up', 'crecer'),
(12, 'Infancia y juventud', 'primary school', 'escuela primaria'),
(12, 'Infancia y juventud', 'high school', 'instituto'),
(12, 'Infancia y juventud', 'to graduate', 'graduarse'),
(12, 'Infancia y juventud', 'degree', 'título (académico)'),
(12, 'Infancia y juventud', 'career', 'carrera profesional'),
(12, 'Infancia y juventud', 'first job', 'primer trabajo'),
(12, 'Infancia y juventud', 'to fall in love', 'enamorarse'),
(12, 'Infancia y juventud', 'boyfriend', 'novio'),
(12, 'Infancia y juventud', 'girlfriend', 'novia'),
(12, 'Infancia y juventud', 'to get engaged', 'comprometerse'),
(12, 'Infancia y juventud', 'wedding', 'boda'),
(12, 'Adultez y vida adulta', 'to get married', 'casarse'),
(12, 'Adultez y vida adulta', 'marriage', 'matrimonio'),
(12, 'Adultez y vida adulta', 'to have children', 'tener hijos'),
(12, 'Adultez y vida adulta', 'to raise', 'criar'),
(12, 'Adultez y vida adulta', 'to retire', 'jubilarse'),
(12, 'Adultez y vida adulta', 'retirement', 'jubilación'),
(12, 'Adultez y vida adulta', 'old age', 'vejez'),
(12, 'Adultez y vida adulta', 'to die', 'morir'),
(12, 'Adultez y vida adulta', 'death', 'muerte'),
(12, 'Adultez y vida adulta', 'funeral', 'funeral'),
(12, 'Adultez y vida adulta', 'to move abroad', 'irse al extranjero'),
(12, 'Adultez y vida adulta', 'to change', 'cambiar'),
(12, 'Adultez y vida adulta', 'success', 'éxito'),
(12, 'Adultez y vida adulta', 'successful', 'exitoso'),
(12, 'Adultez y vida adulta', 'failure', 'fracaso'),
(12, 'Adultez y vida adulta', 'to achieve', 'lograr'),
(12, 'Adultez y vida adulta', 'dream', 'sueño (meta)'),
(12, 'Adultez y vida adulta', 'goal', 'meta'),
(12, 'Adultez y vida adulta', 'memory', 'recuerdo'),
(12, 'Adultez y vida adulta', 'to remember', 'recordar'),
(12, 'Logros e historia', 'to forget', 'olvidar'),
(12, 'Logros e historia', 'past', 'pasado'),
(12, 'Logros e historia', 'event', 'acontecimiento'),
(12, 'Logros e historia', 'important', 'importante'),
(12, 'Logros e historia', 'famous', 'famoso'),
(12, 'Logros e historia', 'biography', 'biografía'),
(12, 'Logros e historia', 'history', 'historia'),
(12, 'Logros e historia', 'war', 'guerra'),
(12, 'Logros e historia', 'peace', 'paz'),
(12, 'Logros e historia', 'to fight', 'luchar'),
(12, 'Logros e historia', 'prize', 'premio'),
(12, 'Logros e historia', 'to become', 'convertirse en'),
(12, 'Logros e historia', 'to found', 'fundar'),
(12, 'Logros e historia', 'to invent', 'inventar'),
(12, 'Logros e historia', 'invention', 'invento'),
(12, 'Logros e historia', 'to discover', 'descubrir'),
(12, 'Logros e historia', 'discovery', 'descubrimiento'),
(12, 'Logros e historia', 'to publish', 'publicar'),
(12, 'Logros e historia', 'experience', 'experiencia'),
(12, 'Logros e historia', 'generation', 'generación');
