-- SEMANA 21 · Trabajo, profesiones y CV · 72 palabras
-- Nota: el título original decía "73 palabras"; transcribiendo la tabla con cuidado
-- solo conté 72. Si tienes el listado en texto plano, dime y reviso la que falte.
insert into words (week, section, en, es) values
(21, 'Trabajo y contratos', 'job', 'trabajo (empleo)'),
(21, 'Trabajo y contratos', 'profession', 'profesión'),
(21, 'Trabajo y contratos', 'occupation', 'ocupación'),
(21, 'Trabajo y contratos', 'employer', 'empleador'),
(21, 'Trabajo y contratos', 'employee', 'empleado'),
(21, 'Trabajo y contratos', 'boss', 'jefe'),
(21, 'Trabajo y contratos', 'colleague', 'compañero de trabajo'),
(21, 'Trabajo y contratos', 'staff', 'personal'),
(21, 'Trabajo y contratos', 'company', 'empresa'),
(21, 'Trabajo y contratos', 'business', 'negocio'),
(21, 'Trabajo y contratos', 'office', 'oficina'),
(21, 'Trabajo y contratos', 'factory', 'fábrica'),
(21, 'Trabajo y contratos', 'department', 'departamento'),
(21, 'Trabajo y contratos', 'position', 'puesto'),
(21, 'Trabajo y contratos', 'task', 'tarea'),
(21, 'Trabajo y contratos', 'duty', 'deber (obligación)'),
(21, 'Trabajo y contratos', 'responsibility', 'responsabilidad'),
(21, 'Trabajo y contratos', 'shift', 'turno'),
(21, 'Trabajo y contratos', 'full-time', 'jornada completa'),
(21, 'Trabajo y contratos', 'part-time', 'media jornada'),
(21, 'Trabajo y contratos', 'contract', 'contrato'),
(21, 'Trabajo y contratos', 'to hire', 'contratar'),
(21, 'Trabajo y contratos', 'application', 'solicitud'),
(21, 'Trabajo y contratos', 'applicant', 'candidato'),
(21, 'Búsqueda de empleo y profesiones', 'CV/resume', 'currículum'),
(21, 'Búsqueda de empleo y profesiones', 'cover letter', 'carta de presentación'),
(21, 'Búsqueda de empleo y profesiones', 'interview', 'entrevista'),
(21, 'Búsqueda de empleo y profesiones', 'to interview', 'entrevistar'),
(21, 'Búsqueda de empleo y profesiones', 'qualification', 'titulación'),
(21, 'Búsqueda de empleo y profesiones', 'requirement', 'requisito'),
(21, 'Búsqueda de empleo y profesiones', 'reference', 'referencia'),
(21, 'Búsqueda de empleo y profesiones', 'to sign', 'firmar'),
(21, 'Búsqueda de empleo y profesiones', 'bonus', 'bonificación'),
(21, 'Búsqueda de empleo y profesiones', 'benefits', 'beneficios (laborales)'),
(21, 'Búsqueda de empleo y profesiones', 'overtime', 'horas extra'),
(21, 'Búsqueda de empleo y profesiones', 'day off', 'día libre'),
(21, 'Búsqueda de empleo y profesiones', 'sick leave', 'baja por enfermedad'),
(21, 'Búsqueda de empleo y profesiones', 'unemployed', 'desempleado'),
(21, 'Búsqueda de empleo y profesiones', 'unemployment', 'desempleo'),
(21, 'Búsqueda de empleo y profesiones', 'to look for a job', 'buscar trabajo'),
(21, 'Búsqueda de empleo y profesiones', 'job offer', 'oferta de trabajo'),
(21, 'Búsqueda de empleo y profesiones', 'doctor', 'médico'),
(21, 'Búsqueda de empleo y profesiones', 'nurse', 'enfermero'),
(21, 'Búsqueda de empleo y profesiones', 'engineer', 'ingeniero'),
(21, 'Búsqueda de empleo y profesiones', 'lawyer', 'abogado'),
(21, 'Búsqueda de empleo y profesiones', 'accountant', 'contable'),
(21, 'Búsqueda de empleo y profesiones', 'architect', 'arquitecto'),
(21, 'Búsqueda de empleo y profesiones', 'journalist', 'periodista'),
(21, 'Búsqueda de empleo y profesiones', 'chef', 'chef'),
(21, 'Oficios y profesiones', 'farmer', 'agricultor'),
(21, 'Oficios y profesiones', 'builder', 'albañil'),
(21, 'Oficios y profesiones', 'electrician', 'electricista'),
(21, 'Oficios y profesiones', 'plumber', 'fontanero'),
(21, 'Oficios y profesiones', 'mechanic', 'mecánico'),
(21, 'Oficios y profesiones', 'hairdresser', 'peluquero'),
(21, 'Oficios y profesiones', 'police officer', 'policía (agente)'),
(21, 'Oficios y profesiones', 'firefighter', 'bombero'),
(21, 'Oficios y profesiones', 'soldier', 'soldado'),
(21, 'Oficios y profesiones', 'pilot', 'piloto'),
(21, 'Oficios y profesiones', 'scientist', 'científico'),
(21, 'Oficios y profesiones', 'translator', 'traductor'),
(21, 'Oficios y profesiones', 'designer', 'diseñador'),
(21, 'Oficios y profesiones', 'salesperson', 'vendedor'),
(21, 'Oficios y profesiones', 'receptionist', 'recepcionista'),
(21, 'Oficios y profesiones', 'manager', 'gerente'),
(21, 'Oficios y profesiones', 'director', 'director'),
(21, 'Oficios y profesiones', 'secretary', 'secretario'),
(21, 'Oficios y profesiones', 'businessman', 'empresario'),
(21, 'Oficios y profesiones', 'freelancer', 'autónomo'),
(21, 'Oficios y profesiones', 'to work from home', 'teletrabajar'),
(21, 'Oficios y profesiones', 'workplace', 'lugar de trabajo'),
(21, 'Oficios y profesiones', 'teamwork', 'trabajo en equipo');
