-- SEMANA 10 · Actividades del fin de semana · 60 palabras
insert into words (week, section, en, es) values
(10, 'Planes de fin de semana', 'to go out', 'salir (de fiesta)'),
(10, 'Planes de fin de semana', 'party', 'fiesta'),
(10, 'Planes de fin de semana', 'to invite', 'invitar'),
(10, 'Planes de fin de semana', 'to meet friends', 'quedar con amigos'),
(10, 'Planes de fin de semana', 'to hang out', 'pasar el rato'),
(10, 'Planes de fin de semana', 'to stay home', 'quedarse en casa'),
(10, 'Planes de fin de semana', 'to relax', 'relajarse'),
(10, 'Planes de fin de semana', 'to sleep in', 'dormir hasta tarde'),
(10, 'Planes de fin de semana', 'barbecue', 'barbacoa'),
(10, 'Planes de fin de semana', 'picnic', 'pícnic'),
(10, 'Planes de fin de semana', 'to go shopping', 'ir de compras'),
(10, 'Planes de fin de semana', 'to go for a walk', 'dar un paseo'),
(10, 'Planes de fin de semana', 'concert', 'concierto'),
(10, 'Planes de fin de semana', 'ticket', 'entrada/billete'),
(10, 'Planes de fin de semana', 'to visit', 'visitar'),
(10, 'Planes de fin de semana', 'beach', 'playa'),
(10, 'Planes de fin de semana', 'pool', 'piscina'),
(10, 'Planes de fin de semana', 'to sunbathe', 'tomar el sol'),
(10, 'Planes de fin de semana', 'countryside', 'campo'),
(10, 'Planes de fin de semana', 'mountain', 'montaña'),
(10, 'Celebraciones', 'to climb', 'escalar'),
(10, 'Celebraciones', 'excursion', 'excursión'),
(10, 'Celebraciones', 'funfair', 'feria'),
(10, 'Celebraciones', 'zoo', 'zoológico'),
(10, 'Celebraciones', 'to laugh', 'reír'),
(10, 'Celebraciones', 'joke', 'chiste'),
(10, 'Celebraciones', 'to celebrate', 'celebrar'),
(10, 'Celebraciones', 'birthday party', 'fiesta de cumpleaños'),
(10, 'Celebraciones', 'gift/present', 'regalo'),
(10, 'Celebraciones', 'balloon', 'globo'),
(10, 'Celebraciones', 'guest', 'invitado'),
(10, 'Celebraciones', 'host', 'anfitrión'),
(10, 'Celebraciones', 'to organize', 'organizar'),
(10, 'Celebraciones', 'plan', 'plan'),
(10, 'Celebraciones', 'to cancel', 'cancelar'),
(10, 'Celebraciones', 'to be busy', 'estar ocupado'),
(10, 'Celebraciones', 'to be free', 'estar libre'),
(10, 'Celebraciones', 'to spend time', 'pasar tiempo'),
(10, 'Celebraciones', 'to have fun', 'divertirse'),
(10, 'Celebraciones', 'to get together', 'reunirse'),
(10, 'Ocio y en casa', 'nightclub', 'discoteca'),
(10, 'Ocio y en casa', 'bar', 'bar'),
(10, 'Ocio y en casa', 'drink', 'bebida'),
(10, 'Ocio y en casa', 'to chat', 'charlar'),
(10, 'Ocio y en casa', 'game', 'juego'),
(10, 'Ocio y en casa', 'to watch a movie', 'ver una película'),
(10, 'Ocio y en casa', 'series', 'serie'),
(10, 'Ocio y en casa', 'episode', 'episodio'),
(10, 'Ocio y en casa', 'bike ride', 'paseo en bici'),
(10, 'Ocio y en casa', 'to take a nap', 'echar una siesta'),
(10, 'Ocio y en casa', 'to play cards', 'jugar a las cartas'),
(10, 'Ocio y en casa', 'to bake', 'hornear'),
(10, 'Ocio y en casa', 'to tidy up', 'ordenar'),
(10, 'Ocio y en casa', 'to do the laundry', 'lavar la ropa'),
(10, 'Ocio y en casa', 'chores', 'tareas del hogar'),
(10, 'Ocio y en casa', 'to walk the dog', 'pasear al perro'),
(10, 'Ocio y en casa', 'to text', 'enviar mensajes'),
(10, 'Ocio y en casa', 'photo', 'foto'),
(10, 'Ocio y en casa', 'to upload', 'subir (a internet)'),
(10, 'Ocio y en casa', 'to rest at home', 'descansar en casa');
