-- SEMANA 24 · Salud, médico y consejos · 71 palabras
insert into words (week, section, en, es) values
(24, 'Síntomas y enfermedades', 'health', 'salud'),
(24, 'Síntomas y enfermedades', 'ill/sick', 'enfermo'),
(24, 'Síntomas y enfermedades', 'disease', 'enfermedad (grave)'),
(24, 'Síntomas y enfermedades', 'symptom', 'síntoma'),
(24, 'Síntomas y enfermedades', 'to feel', 'sentirse'),
(24, 'Síntomas y enfermedades', 'to feel well', 'sentirse bien'),
(24, 'Síntomas y enfermedades', 'to feel bad', 'sentirse mal'),
(24, 'Síntomas y enfermedades', 'headache', 'dolor de cabeza'),
(24, 'Síntomas y enfermedades', 'stomachache', 'dolor de estómago'),
(24, 'Síntomas y enfermedades', 'toothache', 'dolor de muelas'),
(24, 'Síntomas y enfermedades', 'backache', 'dolor de espalda'),
(24, 'Síntomas y enfermedades', 'sore throat', 'dolor de garganta'),
(24, 'Síntomas y enfermedades', 'cough', 'tos'),
(24, 'Síntomas y enfermedades', 'to cough', 'toser'),
(24, 'Síntomas y enfermedades', 'to sneeze', 'estornudar'),
(24, 'Síntomas y enfermedades', 'a cold', 'un resfriado'),
(24, 'Síntomas y enfermedades', 'flu', 'gripe'),
(24, 'Síntomas y enfermedades', 'fever', 'fiebre'),
(24, 'Síntomas y enfermedades', 'allergy', 'alergia'),
(24, 'Síntomas y enfermedades', 'allergic', 'alérgico'),
(24, 'Síntomas y enfermedades', 'infection', 'infección'),
(24, 'Síntomas y enfermedades', 'medicine', 'medicina'),
(24, 'Síntomas y enfermedades', 'pill', 'pastilla'),
(24, 'Síntomas y enfermedades', 'tablet (pill)', 'comprimido'),
(24, 'Tratamiento y médicos', 'syrup', 'jarabe'),
(24, 'Tratamiento y médicos', 'injection', 'inyección'),
(24, 'Tratamiento y médicos', 'vaccine', 'vacuna'),
(24, 'Tratamiento y médicos', 'prescription', 'receta médica'),
(24, 'Tratamiento y médicos', 'dose', 'dosis'),
(24, 'Tratamiento y médicos', 'treatment', 'tratamiento'),
(24, 'Tratamiento y médicos', 'to treat', 'tratar (médicamente)'),
(24, 'Tratamiento y médicos', 'to cure', 'curar'),
(24, 'Tratamiento y médicos', 'cure', 'cura'),
(24, 'Tratamiento y médicos', 'to heal', 'sanar'),
(24, 'Tratamiento y médicos', 'patient', 'paciente'),
(24, 'Tratamiento y médicos', 'dentist', 'dentista'),
(24, 'Tratamiento y médicos', 'surgeon', 'cirujano'),
(24, 'Tratamiento y médicos', 'specialist', 'especialista'),
(24, 'Tratamiento y médicos', 'checkup', 'revisión médica'),
(24, 'Tratamiento y médicos', 'to examine', 'examinar'),
(24, 'Tratamiento y médicos', 'X-ray', 'radiografía'),
(24, 'Tratamiento y médicos', 'medical test', 'análisis médico'),
(24, 'Tratamiento y médicos', 'results', 'resultados'),
(24, 'Tratamiento y médicos', 'diet', 'dieta'),
(24, 'Tratamiento y médicos', 'to be on a diet', 'estar a dieta'),
(24, 'Tratamiento y médicos', 'exercise', 'ejercicio'),
(24, 'Tratamiento y médicos', 'to exercise', 'hacer ejercicio'),
(24, 'Tratamiento y médicos', 'to stay in shape', 'mantenerse en forma'),
(24, 'Consejos y cuerpo', 'stress', 'estrés'),
(24, 'Consejos y cuerpo', 'stressed', 'estresado'),
(24, 'Consejos y cuerpo', 'should', 'debería'),
(24, 'Consejos y cuerpo', 'to advise', 'aconsejar'),
(24, 'Consejos y cuerpo', 'to recommend', 'recomendar'),
(24, 'Consejos y cuerpo', 'recommendation', 'recomendación'),
(24, 'Consejos y cuerpo', 'to avoid', 'evitar'),
(24, 'Consejos y cuerpo', 'to prevent', 'prevenir'),
(24, 'Consejos y cuerpo', 'prevention', 'prevención'),
(24, 'Consejos y cuerpo', 'to take care of', 'cuidar de'),
(24, 'Consejos y cuerpo', 'to look after', 'cuidar'),
(24, 'Consejos y cuerpo', 'hygiene', 'higiene'),
(24, 'Consejos y cuerpo', 'to wash your hands', 'lavarse las manos'),
(24, 'Consejos y cuerpo', 'vitamin', 'vitamina'),
(24, 'Consejos y cuerpo', 'protein', 'proteína'),
(24, 'Consejos y cuerpo', 'to breathe', 'respirar'),
(24, 'Consejos y cuerpo', 'breath', 'respiración'),
(24, 'Consejos y cuerpo', 'heart', 'corazón'),
(24, 'Consejos y cuerpo', 'lungs', 'pulmones'),
(24, 'Consejos y cuerpo', 'stomach', 'estómago'),
(24, 'Consejos y cuerpo', 'skin', 'piel'),
(24, 'Consejos y cuerpo', 'muscle', 'músculo'),
(24, 'Consejos y cuerpo', 'sleep (rest)', 'sueño (descanso)');
