-- SEMANA 6 · Hobbies, deportes y habilidades · 60 palabras
insert into words (week, section, en, es) values
(6, 'Deportes y equipos', 'hobby', 'pasatiempo'),
(6, 'Deportes y equipos', 'free time', 'tiempo libre'),
(6, 'Deportes y equipos', 'sport', 'deporte'),
(6, 'Deportes y equipos', 'football/soccer', 'fútbol'),
(6, 'Deportes y equipos', 'basketball', 'baloncesto'),
(6, 'Deportes y equipos', 'tennis', 'tenis'),
(6, 'Deportes y equipos', 'swimming', 'natación'),
(6, 'Deportes y equipos', 'to swim', 'nadar'),
(6, 'Deportes y equipos', 'cycling', 'ciclismo'),
(6, 'Deportes y equipos', 'to ride a bike', 'montar en bici'),
(6, 'Deportes y equipos', 'gym', 'gimnasio'),
(6, 'Deportes y equipos', 'to train', 'entrenar'),
(6, 'Deportes y equipos', 'match', 'partido'),
(6, 'Deportes y equipos', 'team', 'equipo'),
(6, 'Deportes y equipos', 'player', 'jugador'),
(6, 'Deportes y equipos', 'ball', 'balón'),
(6, 'Deportes y equipos', 'to win', 'ganar'),
(6, 'Deportes y equipos', 'to lose', 'perder'),
(6, 'Deportes y equipos', 'to score', 'marcar (gol)'),
(6, 'Deportes y equipos', 'music', 'música'),
(6, 'Arte, música y juegos', 'to sing', 'cantar'),
(6, 'Arte, música y juegos', 'song', 'canción'),
(6, 'Arte, música y juegos', 'to dance', 'bailar'),
(6, 'Arte, música y juegos', 'to play the guitar', 'tocar la guitarra'),
(6, 'Arte, música y juegos', 'piano', 'piano'),
(6, 'Arte, música y juegos', 'instrument', 'instrumento'),
(6, 'Arte, música y juegos', 'to paint', 'pintar'),
(6, 'Arte, música y juegos', 'to draw', 'dibujar'),
(6, 'Arte, música y juegos', 'photography', 'fotografía'),
(6, 'Arte, música y juegos', 'to take photos', 'hacer fotos'),
(6, 'Arte, música y juegos', 'movie/film', 'película'),
(6, 'Arte, música y juegos', 'to go to the cinema', 'ir al cine'),
(6, 'Arte, música y juegos', 'video game', 'videojuego'),
(6, 'Arte, música y juegos', 'board game', 'juego de mesa'),
(6, 'Arte, música y juegos', 'chess', 'ajedrez'),
(6, 'Arte, música y juegos', 'to collect', 'coleccionar'),
(6, 'Arte, música y juegos', 'to fish', 'pescar'),
(6, 'Arte, música y juegos', 'fishing', 'pesca'),
(6, 'Arte, música y juegos', 'hiking', 'senderismo'),
(6, 'Arte, música y juegos', 'to camp', 'acampar'),
(6, 'Actividades y preferencias', 'to travel', 'viajar'),
(6, 'Actividades y preferencias', 'to sew', 'coser'),
(6, 'Actividades y preferencias', 'to knit', 'tejer'),
(6, 'Actividades y preferencias', 'yoga', 'yoga'),
(6, 'Actividades y preferencias', 'to skate', 'patinar'),
(6, 'Actividades y preferencias', 'to ski', 'esquiar'),
(6, 'Actividades y preferencias', 'surfing', 'surf'),
(6, 'Actividades y preferencias', 'to be good at', 'ser bueno en'),
(6, 'Actividades y preferencias', 'to be able to', 'ser capaz de'),
(6, 'Actividades y preferencias', 'skill', 'habilidad'),
(6, 'Actividades y preferencias', 'to practice', 'practicar'),
(6, 'Actividades y preferencias', 'to enjoy', 'disfrutar'),
(6, 'Actividades y preferencias', 'fun', 'diversión'),
(6, 'Actividades y preferencias', 'boring', 'aburrido'),
(6, 'Actividades y preferencias', 'interesting', 'interesante'),
(6, 'Actividades y preferencias', 'exciting', 'emocionante'),
(6, 'Actividades y preferencias', 'favorite', 'favorito'),
(6, 'Actividades y preferencias', 'to prefer', 'preferir'),
(6, 'Actividades y preferencias', 'running', 'correr (deporte)'),
(6, 'Actividades y preferencias', 'volleyball', 'voleibol');
