-- SEMANA 9 · Comida, bebida y restaurante · 62 palabras
insert into words (week, section, en, es) values
(9, 'Comidas y proteínas', 'food', 'comida'),
(9, 'Comidas y proteínas', 'breakfast', 'desayuno'),
(9, 'Comidas y proteínas', 'lunch', 'almuerzo'),
(9, 'Comidas y proteínas', 'dinner', 'cena'),
(9, 'Comidas y proteínas', 'snack', 'merienda'),
(9, 'Comidas y proteínas', 'bread', 'pan'),
(9, 'Comidas y proteínas', 'butter', 'mantequilla'),
(9, 'Comidas y proteínas', 'cheese', 'queso'),
(9, 'Comidas y proteínas', 'egg', 'huevo'),
(9, 'Comidas y proteínas', 'milk', 'leche'),
(9, 'Comidas y proteínas', 'yogurt', 'yogur'),
(9, 'Comidas y proteínas', 'meat', 'carne'),
(9, 'Comidas y proteínas', 'chicken', 'pollo'),
(9, 'Comidas y proteínas', 'beef', 'carne de res'),
(9, 'Comidas y proteínas', 'pork', 'cerdo (carne)'),
(9, 'Comidas y proteínas', 'fish (food)', 'pescado'),
(9, 'Comidas y proteínas', 'seafood', 'mariscos'),
(9, 'Comidas y proteínas', 'rice', 'arroz'),
(9, 'Comidas y proteínas', 'pasta', 'pasta'),
(9, 'Comidas y proteínas', 'soup', 'sopa'),
(9, 'Comidas y proteínas', 'salad', 'ensalada'),
(9, 'Frutas, verduras y condimentos', 'vegetables', 'verduras'),
(9, 'Frutas, verduras y condimentos', 'fruit', 'fruta'),
(9, 'Frutas, verduras y condimentos', 'apple', 'manzana'),
(9, 'Frutas, verduras y condimentos', 'banana', 'plátano'),
(9, 'Frutas, verduras y condimentos', 'orange', 'naranja'),
(9, 'Frutas, verduras y condimentos', 'strawberry', 'fresa'),
(9, 'Frutas, verduras y condimentos', 'grape', 'uva'),
(9, 'Frutas, verduras y condimentos', 'tomato', 'tomate'),
(9, 'Frutas, verduras y condimentos', 'potato', 'patata'),
(9, 'Frutas, verduras y condimentos', 'onion', 'cebolla'),
(9, 'Frutas, verduras y condimentos', 'garlic', 'ajo'),
(9, 'Frutas, verduras y condimentos', 'carrot', 'zanahoria'),
(9, 'Frutas, verduras y condimentos', 'lettuce', 'lechuga'),
(9, 'Frutas, verduras y condimentos', 'sugar', 'azúcar'),
(9, 'Frutas, verduras y condimentos', 'salt', 'sal'),
(9, 'Frutas, verduras y condimentos', 'pepper', 'pimienta'),
(9, 'Frutas, verduras y condimentos', 'oil', 'aceite'),
(9, 'Frutas, verduras y condimentos', 'sauce', 'salsa'),
(9, 'Frutas, verduras y condimentos', 'dessert', 'postre'),
(9, 'Frutas, verduras y condimentos', 'cake', 'pastel'),
(9, 'Frutas, verduras y condimentos', 'ice cream', 'helado'),
(9, 'Bebidas y en el restaurante', 'chocolate', 'chocolate'),
(9, 'Bebidas y en el restaurante', 'cookie', 'galleta'),
(9, 'Bebidas y en el restaurante', 'water', 'agua'),
(9, 'Bebidas y en el restaurante', 'juice', 'zumo/jugo'),
(9, 'Bebidas y en el restaurante', 'coffee', 'café'),
(9, 'Bebidas y en el restaurante', 'tea', 'té'),
(9, 'Bebidas y en el restaurante', 'beer', 'cerveza'),
(9, 'Bebidas y en el restaurante', 'wine', 'vino'),
(9, 'Bebidas y en el restaurante', 'soft drink', 'refresco'),
(9, 'Bebidas y en el restaurante', 'menu', 'menú'),
(9, 'Bebidas y en el restaurante', 'waiter', 'camarero'),
(9, 'Bebidas y en el restaurante', 'bill/check', 'cuenta'),
(9, 'Bebidas y en el restaurante', 'tip', 'propina'),
(9, 'Bebidas y en el restaurante', 'to order', 'pedir (comida)'),
(9, 'Bebidas y en el restaurante', 'delicious', 'delicioso'),
(9, 'Bebidas y en el restaurante', 'sweet', 'dulce'),
(9, 'Bebidas y en el restaurante', 'salty', 'salado'),
(9, 'Bebidas y en el restaurante', 'hungry', 'hambriento'),
(9, 'Bebidas y en el restaurante', 'thirsty', 'sediento'),
(9, 'Bebidas y en el restaurante', 'to taste', 'probar (sabor)');
