-- SEMANA 25 · Medio ambiente y reciclaje · 70 palabras
insert into words (week, section, en, es) values
(25, 'Contaminación y energía', 'environment', 'medio ambiente'),
(25, 'Contaminación y energía', 'environmental', 'ambiental'),
(25, 'Contaminación y energía', 'pollution', 'contaminación'),
(25, 'Contaminación y energía', 'to pollute', 'contaminar'),
(25, 'Contaminación y energía', 'air pollution', 'contaminación del aire'),
(25, 'Contaminación y energía', 'climate', 'clima'),
(25, 'Contaminación y energía', 'climate change', 'cambio climático'),
(25, 'Contaminación y energía', 'global warming', 'calentamiento global'),
(25, 'Contaminación y energía', 'greenhouse effect', 'efecto invernadero'),
(25, 'Contaminación y energía', 'carbon dioxide', 'dióxido de carbono'),
(25, 'Contaminación y energía', 'emission', 'emisión'),
(25, 'Contaminación y energía', 'fossil fuels', 'combustibles fósiles'),
(25, 'Contaminación y energía', 'oil (petroleum)', 'petróleo'),
(25, 'Contaminación y energía', 'coal', 'carbón'),
(25, 'Contaminación y energía', 'gas', 'gas'),
(25, 'Contaminación y energía', 'energy', 'energía'),
(25, 'Contaminación y energía', 'renewable energy', 'energía renovable'),
(25, 'Contaminación y energía', 'solar power', 'energía solar'),
(25, 'Contaminación y energía', 'wind power', 'energía eólica'),
(25, 'Contaminación y energía', 'solar panel', 'panel solar'),
(25, 'Contaminación y energía', 'electricity', 'electricidad'),
(25, 'Contaminación y energía', 'to waste', 'desperdiciar'),
(25, 'Contaminación y energía', 'waste', 'residuos'),
(25, 'Contaminación y energía', 'rubbish/garbage', 'basura'),
(25, 'Reciclaje', 'litter', 'basura tirada'),
(25, 'Reciclaje', 'to throw away', 'tirar (a la basura)'),
(25, 'Reciclaje', 'bin', 'cubo de basura'),
(25, 'Reciclaje', 'landfill', 'vertedero'),
(25, 'Reciclaje', 'to recycle', 'reciclar'),
(25, 'Reciclaje', 'recycling', 'reciclaje'),
(25, 'Reciclaje', 'reusable', 'reutilizable'),
(25, 'Reciclaje', 'to reuse', 'reutilizar'),
(25, 'Reciclaje', 'to reduce', 'reducir'),
(25, 'Reciclaje', 'plastic', 'plástico'),
(25, 'Reciclaje', 'glass', 'vidrio'),
(25, 'Reciclaje', 'paper', 'papel'),
(25, 'Reciclaje', 'cardboard', 'cartón'),
(25, 'Reciclaje', 'metal', 'metal'),
(25, 'Reciclaje', 'container', 'contenedor'),
(25, 'Reciclaje', 'packaging', 'embalaje'),
(25, 'Reciclaje', 'to protect', 'proteger'),
(25, 'Reciclaje', 'protection', 'protección'),
(25, 'Reciclaje', 'to destroy', 'destruir'),
(25, 'Reciclaje', 'destruction', 'destrucción'),
(25, 'Reciclaje', 'deforestation', 'deforestación'),
(25, 'Reciclaje', 'to cut down', 'talar'),
(25, 'Reciclaje', 'endangered species', 'especies en peligro'),
(25, 'Reciclaje', 'extinct', 'extinto'),
(25, 'Naturaleza y sostenibilidad', 'extinction', 'extinción'),
(25, 'Naturaleza y sostenibilidad', 'wildlife', 'fauna'),
(25, 'Naturaleza y sostenibilidad', 'habitat', 'hábitat'),
(25, 'Naturaleza y sostenibilidad', 'ecosystem', 'ecosistema'),
(25, 'Naturaleza y sostenibilidad', 'resources', 'recursos'),
(25, 'Naturaleza y sostenibilidad', 'natural resources', 'recursos naturales'),
(25, 'Naturaleza y sostenibilidad', 'to run out of', 'agotarse'),
(25, 'Naturaleza y sostenibilidad', 'shortage', 'escasez'),
(25, 'Naturaleza y sostenibilidad', 'drought', 'sequía'),
(25, 'Naturaleza y sostenibilidad', 'to plant trees', 'plantar árboles'),
(25, 'Naturaleza y sostenibilidad', 'organic', 'orgánico/ecológico'),
(25, 'Naturaleza y sostenibilidad', 'sustainable', 'sostenible'),
(25, 'Naturaleza y sostenibilidad', 'sustainability', 'sostenibilidad'),
(25, 'Naturaleza y sostenibilidad', 'eco-friendly', 'ecológico'),
(25, 'Naturaleza y sostenibilidad', 'to care about', 'preocuparse por'),
(25, 'Naturaleza y sostenibilidad', 'responsible', 'responsable'),
(25, 'Naturaleza y sostenibilidad', 'to take action', 'actuar/tomar medidas'),
(25, 'Naturaleza y sostenibilidad', 'campaign', 'campaña'),
(25, 'Naturaleza y sostenibilidad', 'to raise awareness', 'concienciar'),
(25, 'Naturaleza y sostenibilidad', 'future generations', 'generaciones futuras'),
(25, 'Naturaleza y sostenibilidad', 'solution', 'solución'),
(25, 'Naturaleza y sostenibilidad', 'to solve', 'resolver');
