-- SEMANA 20 · Noticias personales y cambios · 71 palabras
insert into words (week, section, en, es) values
(20, 'Noticias y cambios de vida', 'news', 'noticias'),
(20, 'Noticias y cambios de vida', 'piece of news', 'una noticia'),
(20, 'Noticias y cambios de vida', 'to announce', 'anunciar'),
(20, 'Noticias y cambios de vida', 'announcement', 'anuncio (aviso)'),
(20, 'Noticias y cambios de vida', 'to find out', 'enterarse'),
(20, 'Noticias y cambios de vida', 'to hear about', 'oír hablar de'),
(20, 'Noticias y cambios de vida', 'recently', 'recientemente'),
(20, 'Noticias y cambios de vida', 'lately', 'últimamente'),
(20, 'Noticias y cambios de vida', 'these days', 'en estos días'),
(20, 'Noticias y cambios de vida', 'change of plans', 'cambio de planes'),
(20, 'Noticias y cambios de vida', 'to move out', 'irse de casa'),
(20, 'Noticias y cambios de vida', 'to move in', 'mudarse a (entrar)'),
(20, 'Noticias y cambios de vida', 'new job', 'trabajo nuevo'),
(20, 'Noticias y cambios de vida', 'to get a job', 'conseguir trabajo'),
(20, 'Noticias y cambios de vida', 'to quit', 'renunciar'),
(20, 'Noticias y cambios de vida', 'to be fired', 'ser despedido'),
(20, 'Noticias y cambios de vida', 'to be promoted', 'ser ascendido'),
(20, 'Noticias y cambios de vida', 'promotion', 'ascenso'),
(20, 'Noticias y cambios de vida', 'to get a raise', 'recibir un aumento'),
(20, 'Noticias y cambios de vida', 'to start a business', 'montar un negocio'),
(20, 'Noticias y cambios de vida', 'to break up', 'romper (pareja)'),
(20, 'Noticias y cambios de vida', 'to get back together', 'volver (pareja)'),
(20, 'Noticias y cambios de vida', 'pregnant', 'embarazada'),
(20, 'Noticias y cambios de vida', 'to give birth', 'dar a luz'),
(20, 'Trabajo, salud y hábitos', 'newborn', 'recién nacido'),
(20, 'Trabajo, salud y hábitos', 'to adopt', 'adoptar'),
(20, 'Trabajo, salud y hábitos', 'to buy a house', 'comprar una casa'),
(20, 'Trabajo, salud y hábitos', 'to pass an exam', 'aprobar un examen'),
(20, 'Trabajo, salud y hábitos', 'to fail an exam', 'suspender un examen'),
(20, 'Trabajo, salud y hábitos', 'to enroll', 'matricularse'),
(20, 'Trabajo, salud y hábitos', 'course', 'curso'),
(20, 'Trabajo, salud y hábitos', 'to sign up for', 'apuntarse a'),
(20, 'Trabajo, salud y hábitos', 'to lose weight', 'perder peso'),
(20, 'Trabajo, salud y hábitos', 'to gain weight', 'ganar peso'),
(20, 'Trabajo, salud y hábitos', 'to get fit', 'ponerse en forma'),
(20, 'Trabajo, salud y hábitos', 'to give up smoking', 'dejar de fumar'),
(20, 'Trabajo, salud y hábitos', 'habit', 'hábito'),
(20, 'Trabajo, salud y hábitos', 'routine', 'rutina'),
(20, 'Trabajo, salud y hábitos', 'lifestyle', 'estilo de vida'),
(20, 'Trabajo, salud y hábitos', 'healthy', 'saludable'),
(20, 'Trabajo, salud y hábitos', 'unhealthy', 'poco saludable'),
(20, 'Trabajo, salud y hábitos', 'to recover', 'recuperarse'),
(20, 'Trabajo, salud y hábitos', 'to get sick', 'enfermarse'),
(20, 'Trabajo, salud y hábitos', 'illness', 'enfermedad'),
(20, 'Trabajo, salud y hábitos', 'surgery', 'cirugía'),
(20, 'Trabajo, salud y hábitos', 'to turn (age)', 'cumplir (años)'),
(20, 'Trabajo, salud y hábitos', 'milestone', 'hito'),
(20, 'Trabajo, salud y hábitos', 'achievement', 'logro'),
(20, 'Reacciones y nuevos comienzos', 'good news', 'buenas noticias'),
(20, 'Reacciones y nuevos comienzos', 'bad news', 'malas noticias'),
(20, 'Reacciones y nuevos comienzos', 'gossip', 'chisme'),
(20, 'Reacciones y nuevos comienzos', 'rumor', 'rumor'),
(20, 'Reacciones y nuevos comienzos', 'to spread', 'difundirse'),
(20, 'Reacciones y nuevos comienzos', 'surprised', 'sorprendido'),
(20, 'Reacciones y nuevos comienzos', 'shocked', 'impactado'),
(20, 'Reacciones y nuevos comienzos', 'disappointed', 'decepcionado'),
(20, 'Reacciones y nuevos comienzos', 'delighted', 'encantado (contento)'),
(20, 'Reacciones y nuevos comienzos', 'relieved', 'aliviado'),
(20, 'Reacciones y nuevos comienzos', 'worried', 'preocupado'),
(20, 'Reacciones y nuevos comienzos', 'to worry', 'preocuparse'),
(20, 'Reacciones y nuevos comienzos', 'to calm down', 'calmarse'),
(20, 'Reacciones y nuevos comienzos', 'to cheer up', 'animarse'),
(20, 'Reacciones y nuevos comienzos', 'to support', 'apoyar'),
(20, 'Reacciones y nuevos comienzos', 'support', 'apoyo'),
(20, 'Reacciones y nuevos comienzos', 'to keep in touch', 'mantener el contacto'),
(20, 'Reacciones y nuevos comienzos', 'to lose touch', 'perder el contacto'),
(20, 'Reacciones y nuevos comienzos', 'to catch up', 'ponerse al día'),
(20, 'Reacciones y nuevos comienzos', 'guess what', 'adivina qué'),
(20, 'Reacciones y nuevos comienzos', 'to settle down', 'establecerse'),
(20, 'Reacciones y nuevos comienzos', 'fresh start', 'nuevo comienzo'),
(20, 'Reacciones y nuevos comienzos', 'turning point', 'punto de inflexión');
