-- SEMANA 29 · Cultura, cine y arte · 70 palabras
insert into words (week, section, en, es) values
(29, 'Arte y literatura', 'cultural', 'cultural'),
(29, 'Arte y literatura', 'art', 'arte'),
(29, 'Arte y literatura', 'artist', 'artista'),
(29, 'Arte y literatura', 'painting', 'pintura (cuadro)'),
(29, 'Arte y literatura', 'painter', 'pintor'),
(29, 'Arte y literatura', 'sculpture', 'escultura'),
(29, 'Arte y literatura', 'exhibition', 'exposición'),
(29, 'Arte y literatura', 'gallery', 'galería'),
(29, 'Arte y literatura', 'masterpiece', 'obra maestra'),
(29, 'Arte y literatura', 'literature', 'literatura'),
(29, 'Arte y literatura', 'writer', 'escritor'),
(29, 'Arte y literatura', 'author', 'autor'),
(29, 'Arte y literatura', 'novel', 'novela'),
(29, 'Arte y literatura', 'poem', 'poema'),
(29, 'Arte y literatura', 'poet', 'poeta'),
(29, 'Arte y literatura', 'poetry', 'poesía'),
(29, 'Arte y literatura', 'chapter', 'capítulo'),
(29, 'Arte y literatura', 'tale', 'cuento'),
(29, 'Arte y literatura', 'fiction', 'ficción'),
(29, 'Arte y literatura', 'non-fiction', 'no ficción'),
(29, 'Arte y literatura', 'mystery', 'misterio'),
(29, 'Arte y literatura', 'romance (genre)', 'romance (género)'),
(29, 'Arte y literatura', 'science fiction', 'ciencia ficción'),
(29, 'Arte y literatura', 'horror', 'terror'),
(29, 'Cine', 'comedy', 'comedia'),
(29, 'Cine', 'drama', 'drama'),
(29, 'Cine', 'action (genre)', 'acción (género)'),
(29, 'Cine', 'thriller', 'suspense'),
(29, 'Cine', 'documentary', 'documental'),
(29, 'Cine', 'cartoon', 'dibujos animados'),
(29, 'Cine', 'animation', 'animación'),
(29, 'Cine', 'film director', 'director de cine'),
(29, 'Cine', 'actor', 'actor'),
(29, 'Cine', 'actress', 'actriz'),
(29, 'Cine', 'cast', 'reparto'),
(29, 'Cine', 'main character', 'protagonista'),
(29, 'Cine', 'villain', 'villano'),
(29, 'Cine', 'scene', 'escena'),
(29, 'Cine', 'script', 'guion'),
(29, 'Cine', 'soundtrack', 'banda sonora'),
(29, 'Cine', 'special effects', 'efectos especiales'),
(29, 'Cine', 'subtitle', 'subtítulo'),
(29, 'Cine', 'dubbed', 'doblado'),
(29, 'Cine', 'premiere', 'estreno'),
(29, 'Cine', 'review', 'reseña'),
(29, 'Cine', 'rating', 'calificación'),
(29, 'Cine', 'award', 'premio(galardon)'),
(29, 'Cine', 'performance', 'actuación'),
(29, 'Teatro, música y patrimonio', 'to perform', 'actuar/interpretar'),
(29, 'Teatro, música y patrimonio', 'stage (theater)', 'escenario'),
(29, 'Teatro, música y patrimonio', 'play (theater)', 'obra de teatro'),
(29, 'Teatro, música y patrimonio', 'musical', 'musical'),
(29, 'Teatro, música y patrimonio', 'opera', 'ópera'),
(29, 'Teatro, música y patrimonio', 'ballet', 'ballet'),
(29, 'Teatro, música y patrimonio', 'dance (art)', 'danza'),
(29, 'Teatro, música y patrimonio', 'orchestra', 'orquesta'),
(29, 'Teatro, música y patrimonio', 'band', 'banda (música)'),
(29, 'Teatro, música y patrimonio', 'singer', 'cantante'),
(29, 'Teatro, música y patrimonio', 'album', 'álbum'),
(29, 'Teatro, música y patrimonio', 'lyrics', 'letra (de canción)'),
(29, 'Teatro, música y patrimonio', 'rhythm', 'ritmo'),
(29, 'Teatro, música y patrimonio', 'melody', 'melodía'),
(29, 'Teatro, música y patrimonio', 'genre', 'género'),
(29, 'Teatro, música y patrimonio', 'classical music', 'música clásica'),
(29, 'Teatro, música y patrimonio', 'folklore', 'folclore'),
(29, 'Teatro, música y patrimonio', 'heritage', 'patrimonio'),
(29, 'Teatro, música y patrimonio', 'costume', 'disfraz/vestuario'),
(29, 'Teatro, música y patrimonio', 'ticket office', 'taquilla'),
(29, 'Teatro, música y patrimonio', 'to entertain', 'entretener'),
(29, 'Teatro, música y patrimonio', 'entertainment', 'entretenimiento');
