-- SEMANA 11 · Viajes, transporte y vacaciones · 60 palabras
insert into words (week, section, en, es) values
(11, 'Viajes y equipaje', 'trip', 'viaje'),
(11, 'Viajes y equipaje', 'journey', 'trayecto'),
(11, 'Viajes y equipaje', 'travel agency', 'agencia de viajes'),
(11, 'Viajes y equipaje', 'tourist', 'turista'),
(11, 'Viajes y equipaje', 'tourism', 'turismo'),
(11, 'Viajes y equipaje', 'vacation/holidays', 'vacaciones'),
(11, 'Viajes y equipaje', 'suitcase', 'maleta'),
(11, 'Viajes y equipaje', 'luggage', 'equipaje'),
(11, 'Viajes y equipaje', 'backpack', 'mochila'),
(11, 'Viajes y equipaje', 'passport', 'pasaporte'),
(11, 'Viajes y equipaje', 'visa', 'visado'),
(11, 'Viajes y equipaje', 'boarding pass', 'tarjeta de embarque'),
(11, 'Viajes y equipaje', 'flight', 'vuelo'),
(11, 'Viajes y equipaje', 'plane', 'avión'),
(11, 'Viajes y equipaje', 'to fly', 'volar'),
(11, 'Viajes y equipaje', 'to land', 'aterrizar'),
(11, 'Viajes y equipaje', 'to take off (plane)', 'despegar'),
(11, 'Viajes y equipaje', 'train', 'tren'),
(11, 'Viajes y equipaje', 'bus', 'autobús'),
(11, 'Viajes y equipaje', 'subway', 'metro'),
(11, 'Transporte y alojamiento', 'taxi', 'taxi'),
(11, 'Transporte y alojamiento', 'car', 'coche'),
(11, 'Transporte y alojamiento', 'motorbike', 'moto'),
(11, 'Transporte y alojamiento', 'bicycle', 'bicicleta'),
(11, 'Transporte y alojamiento', 'boat', 'barco'),
(11, 'Transporte y alojamiento', 'cruise', 'crucero'),
(11, 'Transporte y alojamiento', 'ferry', 'ferri'),
(11, 'Transporte y alojamiento', 'platform', 'andén'),
(11, 'Transporte y alojamiento', 'seat', 'asiento'),
(11, 'Transporte y alojamiento', 'driver', 'conductor'),
(11, 'Transporte y alojamiento', 'passenger', 'pasajero'),
(11, 'Transporte y alojamiento', 'to book', 'reservar'),
(11, 'Transporte y alojamiento', 'reservation', 'reserva'),
(11, 'Transporte y alojamiento', 'hostel', 'albergue'),
(11, 'Transporte y alojamiento', 'reception', 'recepción'),
(11, 'Transporte y alojamiento', 'to check in', 'registrarse (hotel)'),
(11, 'Transporte y alojamiento', 'to check out', 'dejar el hotel'),
(11, 'Transporte y alojamiento', 'guide', 'guía'),
(11, 'Transporte y alojamiento', 'tour', 'tour'),
(11, 'Transporte y alojamiento', 'sightseeing', 'visitas turísticas'),
(11, 'En el destino', 'monument', 'monumento'),
(11, 'En el destino', 'souvenir', 'recuerdo (objeto)'),
(11, 'En el destino', 'camera', 'cámara'),
(11, 'En el destino', 'to pack', 'hacer la maleta'),
(11, 'En el destino', 'abroad', 'en el extranjero'),
(11, 'En el destino', 'border', 'frontera'),
(11, 'En el destino', 'customs', 'aduana'),
(11, 'En el destino', 'currency', 'moneda (divisa)'),
(11, 'En el destino', 'to exchange money', 'cambiar dinero'),
(11, 'En el destino', 'insurance', 'seguro'),
(11, 'En el destino', 'delay', 'retraso'),
(11, 'En el destino', 'to miss (the train)', 'perder (el tren)'),
(11, 'En el destino', 'to catch', 'coger/alcanzar'),
(11, 'En el destino', 'arrival', 'llegada'),
(11, 'En el destino', 'departure', 'salida'),
(11, 'En el destino', 'destination', 'destino'),
(11, 'En el destino', 'route', 'ruta'),
(11, 'En el destino', 'to rent a car', 'alquilar un coche'),
(11, 'En el destino', 'road trip', 'viaje por carretera'),
(11, 'En el destino', 'island trip', 'viaje a una isla');
