-- SEMANA 23 · Accidentes, emergencias y salud básica · 71 palabras
insert into words (week, section, en, es) values
(23, 'Accidentes y heridas', 'accident', 'accidente'),
(23, 'Accidentes y heridas', 'emergency', 'emergencia'),
(23, 'Accidentes y heridas', 'danger', 'peligro'),
(23, 'Accidentes y heridas', 'help!', '¡socorro!'),
(23, 'Accidentes y heridas', 'to call 112/911', 'llamar a emergencias'),
(23, 'Accidentes y heridas', 'ambulance', 'ambulancia'),
(23, 'Accidentes y heridas', 'the police', 'la policía (cuerpo)'),
(23, 'Accidentes y heridas', 'fire', 'fuego/incendio'),
(23, 'Accidentes y heridas', 'smoke', 'humo'),
(23, 'Accidentes y heridas', 'to burn', 'quemar(se)'),
(23, 'Accidentes y heridas', 'burn', 'quemadura'),
(23, 'Accidentes y heridas', 'to hurt', 'hacer(se) daño'),
(23, 'Accidentes y heridas', 'to injure', 'lesionar'),
(23, 'Accidentes y heridas', 'injury', 'lesión'),
(23, 'Accidentes y heridas', 'injured', 'herido'),
(23, 'Accidentes y heridas', 'wound', 'herida'),
(23, 'Accidentes y heridas', 'to bleed', 'sangrar'),
(23, 'Accidentes y heridas', 'blood', 'sangre'),
(23, 'Accidentes y heridas', 'to fall down', 'caerse'),
(23, 'Accidentes y heridas', 'to faint', 'desmayarse'),
(23, 'Accidentes y heridas', 'unconscious', 'inconsciente'),
(23, 'Accidentes y heridas', 'to break a leg', 'romperse una pierna'),
(23, 'Accidentes y heridas', 'bone', 'hueso'),
(23, 'Accidentes y heridas', 'sprain', 'esguince'),
(23, 'Lesiones y primeros auxilios', 'to twist', 'torcerse'),
(23, 'Lesiones y primeros auxilios', 'bruise', 'moratón'),
(23, 'Lesiones y primeros auxilios', 'cut', 'corte'),
(23, 'Lesiones y primeros auxilios', 'to cut oneself', 'cortarse'),
(23, 'Lesiones y primeros auxilios', 'scar', 'cicatriz'),
(23, 'Lesiones y primeros auxilios', 'pain', 'dolor'),
(23, 'Lesiones y primeros auxilios', 'painful', 'doloroso'),
(23, 'Lesiones y primeros auxilios', 'to suffer', 'sufrir'),
(23, 'Lesiones y primeros auxilios', 'victim', 'víctima'),
(23, 'Lesiones y primeros auxilios', 'witness', 'testigo'),
(23, 'Lesiones y primeros auxilios', 'to witness', 'presenciar'),
(23, 'Lesiones y primeros auxilios', 'to rescue', 'rescatar'),
(23, 'Lesiones y primeros auxilios', 'rescue', 'rescate'),
(23, 'Lesiones y primeros auxilios', 'to save (a life)', 'salvar (una vida)'),
(23, 'Lesiones y primeros auxilios', 'first aid', 'primeros auxilios'),
(23, 'Lesiones y primeros auxilios', 'bandage', 'venda'),
(23, 'Lesiones y primeros auxilios', 'band-aid/plaster', 'tirita'),
(23, 'Lesiones y primeros auxilios', 'stretcher', 'camilla'),
(23, 'Lesiones y primeros auxilios', 'wheelchair', 'silla de ruedas'),
(23, 'Lesiones y primeros auxilios', 'crutches', 'muletas'),
(23, 'Lesiones y primeros auxilios', 'emergency room', 'urgencias'),
(23, 'Lesiones y primeros auxilios', 'to crash', 'chocar'),
(23, 'Lesiones y primeros auxilios', 'crash', 'choque'),
(23, 'Lesiones y primeros auxilios', 'car accident', 'accidente de coche'),
(23, 'Emergencias naturales y seguridad', 'to run over', 'atropellar'),
(23, 'Emergencias naturales y seguridad', 'seatbelt', 'cinturón de seguridad'),
(23, 'Emergencias naturales y seguridad', 'helmet', 'casco'),
(23, 'Emergencias naturales y seguridad', 'to drown', 'ahogarse'),
(23, 'Emergencias naturales y seguridad', 'flood', 'inundación'),
(23, 'Emergencias naturales y seguridad', 'earthquake', 'terremoto'),
(23, 'Emergencias naturales y seguridad', 'lightning', 'rayo'),
(23, 'Emergencias naturales y seguridad', 'thunder', 'trueno'),
(23, 'Emergencias naturales y seguridad', 'to warn', 'advertir'),
(23, 'Emergencias naturales y seguridad', 'warning', 'advertencia'),
(23, 'Emergencias naturales y seguridad', 'alarm', 'alarma'),
(23, 'Emergencias naturales y seguridad', 'to evacuate', 'evacuar'),
(23, 'Emergencias naturales y seguridad', 'safety', 'seguridad'),
(23, 'Emergencias naturales y seguridad', 'careful', 'cuidadoso'),
(23, 'Emergencias naturales y seguridad', 'to be careful', 'tener cuidado'),
(23, 'Emergencias naturales y seguridad', 'to shout for help', 'pedir ayuda a gritos'),
(23, 'Emergencias naturales y seguridad', 'calm', 'tranquilo/calmado'),
(23, 'Emergencias naturales y seguridad', 'to panic', 'entrar en pánico'),
(23, 'Emergencias naturales y seguridad', 'shock', 'conmoción'),
(23, 'Emergencias naturales y seguridad', 'to survive', 'sobrevivir'),
(23, 'Emergencias naturales y seguridad', 'survivor', 'superviviente'),
(23, 'Emergencias naturales y seguridad', 'to report', 'denunciar/informar'),
(23, 'Emergencias naturales y seguridad', 'thief', 'ladrón');
