-- SEMANA 26 · Situaciones hipotéticas y sueños · 70 palabras
insert into words (week, section, en, es) values
(26, 'Condicionales e imaginación', 'to imagine', 'imaginar'),
(26, 'Condicionales e imaginación', 'imagination', 'imaginación'),
(26, 'Condicionales e imaginación', 'imaginary', 'imaginario'),
(26, 'Condicionales e imaginación', 'hypothetical', 'hipotético'),
(26, 'Condicionales e imaginación', 'situation', 'situación'),
(26, 'Condicionales e imaginación', 'if', 'si (condicional)'),
(26, 'Condicionales e imaginación', 'unless', 'a menos que'),
(26, 'Condicionales e imaginación', 'in case', 'por si acaso'),
(26, 'Condicionales e imaginación', 'would', 'condicional (verbo)'),
(26, 'Condicionales e imaginación', 'could', 'podría'),
(26, 'Condicionales e imaginación', 'might', 'podría (quizás)'),
(26, 'Condicionales e imaginación', 'to wish', 'desear'),
(26, 'Condicionales e imaginación', 'wish', 'deseo'),
(26, 'Condicionales e imaginación', 'desire', 'anhelo'),
(26, 'Condicionales e imaginación', 'daydream', 'ensoñación'),
(26, 'Condicionales e imaginación', 'fantasy', 'fantasía'),
(26, 'Condicionales e imaginación', 'ideal', 'ideal'),
(26, 'Condicionales e imaginación', 'perfect', 'perfecto'),
(26, 'Condicionales e imaginación', 'to win the lottery', 'ganar la lotería'),
(26, 'Condicionales e imaginación', 'lottery', 'lotería'),
(26, 'Condicionales e imaginación', 'millionaire', 'millonario'),
(26, 'Condicionales e imaginación', 'fortune', 'fortuna'),
(26, 'Condicionales e imaginación', 'wealth', 'riqueza'),
(26, 'Condicionales e imaginación', 'wealthy', 'adinerado'),
(26, 'Poder y fantasía', 'fame', 'fama'),
(26, 'Poder y fantasía', 'to be famous', 'ser famoso'),
(26, 'Poder y fantasía', 'power', 'poder'),
(26, 'Poder y fantasía', 'powerful', 'poderoso'),
(26, 'Poder y fantasía', 'to rule', 'gobernar'),
(26, 'Poder y fantasía', 'king', 'rey'),
(26, 'Poder y fantasía', 'queen', 'reina'),
(26, 'Poder y fantasía', 'president', 'presidente'),
(26, 'Poder y fantasía', 'to change the world', 'cambiar el mundo'),
(26, 'Poder y fantasía', 'superpower', 'superpoder'),
(26, 'Poder y fantasía', 'invisible', 'invisible'),
(26, 'Poder y fantasía', 'to travel in time', 'viajar en el tiempo'),
(26, 'Poder y fantasía', 'time machine', 'máquina del tiempo'),
(26, 'Poder y fantasía', 'magic', 'magia'),
(26, 'Poder y fantasía', 'magical', 'mágico'),
(26, 'Poder y fantasía', 'wizard', 'mago'),
(26, 'Poder y fantasía', 'genie', 'genio (de la lámpara)'),
(26, 'Poder y fantasía', 'to grant a wish', 'conceder un deseo'),
(26, 'Poder y fantasía', 'possibility', 'posibilidad'),
(26, 'Poder y fantasía', 'alternative', 'alternativa'),
(26, 'Poder y fantasía', 'consequence', 'consecuencia'),
(26, 'Poder y fantasía', 'result', 'resultado'),
(26, 'Poder y fantasía', 'to depend on', 'depender de'),
(26, 'Poder y fantasía', 'condition', 'condición'),
(26, 'Hipótesis y decisiones', 'to suppose', 'suponer'),
(26, 'Hipótesis y decisiones', 'supposing', 'suponiendo que'),
(26, 'Hipótesis y decisiones', 'what if...?', '¿y si...?'),
(26, 'Hipótesis y decisiones', 'if I were you', 'yo en tu lugar'),
(26, 'Hipótesis y decisiones', 'otherwise', 'de lo contrario'),
(26, 'Hipótesis y decisiones', 'instead', 'en cambio'),
(26, 'Hipótesis y decisiones', 'instead of', 'en lugar de'),
(26, 'Hipótesis y decisiones', 'would rather', 'preferiría'),
(26, 'Hipótesis y decisiones', 'scenario', 'escenario'),
(26, 'Hipótesis y decisiones', 'to pretend', 'fingir'),
(26, 'Hipótesis y decisiones', 'to come true', 'hacerse realidad'),
(26, 'Hipótesis y decisiones', 'reality', 'realidad'),
(26, 'Hipótesis y decisiones', 'real', 'real'),
(26, 'Hipótesis y decisiones', 'unreal', 'irreal'),
(26, 'Hipótesis y decisiones', 'desert island', 'isla desierta'),
(26, 'Hipótesis y decisiones', 'treasure', 'tesoro'),
(26, 'Hipótesis y decisiones', 'secret', 'secreto'),
(26, 'Hipótesis y decisiones', 'to keep a secret', 'guardar un secreto'),
(26, 'Hipótesis y decisiones', 'to make a decision', 'tomar una decisión'),
(26, 'Hipótesis y decisiones', 'to take a chance', 'arriesgarse'),
(26, 'Hipótesis y decisiones', 'to have the chance', 'tener la oportunidad'),
(26, 'Hipótesis y decisiones', 'opportunity of a lifetime', 'oportunidad única');
