-- SEMANA 22 · Historias y anécdotas · 72 palabras
insert into words (week, section, en, es) values
(22, 'Narrar una historia', 'story', 'historia (relato)'),
(22, 'Narrar una historia', 'anecdote', 'anécdota'),
(22, 'Narrar una historia', 'to happen', 'pasar/ocurrir'),
(22, 'Narrar una historia', 'suddenly', 'de repente'),
(22, 'Narrar una historia', 'unexpectedly', 'inesperadamente'),
(22, 'Narrar una historia', 'at that moment', 'en ese momento'),
(22, 'Narrar una historia', 'meanwhile', 'mientras tanto'),
(22, 'Narrar una historia', 'while', 'mientras'),
(22, 'Narrar una historia', 'when', 'cuando'),
(22, 'Narrar una historia', 'after that', 'después de eso'),
(22, 'Narrar una historia', 'at first', 'al principio'),
(22, 'Narrar una historia', 'in the end', 'al final'),
(22, 'Narrar una historia', 'luckily', 'por suerte'),
(22, 'Narrar una historia', 'unfortunately', 'por desgracia'),
(22, 'Narrar una historia', 'fortunately', 'afortunadamente'),
(22, 'Narrar una historia', 'apparently', 'al parecer'),
(22, 'Narrar una historia', 'it turned out that', 'resultó que'),
(22, 'Narrar una historia', 'once upon a time', 'érase una vez'),
(22, 'Narrar una historia', 'character', 'personaje'),
(22, 'Narrar una historia', 'beginning', 'principio'),
(22, 'Narrar una historia', 'middle', 'mitad/medio'),
(22, 'Narrar una historia', 'end', 'final'),
(22, 'Narrar una historia', 'to describe', 'describir'),
(22, 'Narrar una historia', 'description', 'descripción'),
(22, 'Acción y percepción', 'detail', 'detalle'),
(22, 'Acción y percepción', 'to mention', 'mencionar'),
(22, 'Acción y percepción', 'to explain', 'explicar'),
(22, 'Acción y percepción', 'explanation', 'explicación'),
(22, 'Acción y percepción', 'to notice', 'notar/fijarse'),
(22, 'Acción y percepción', 'to realize', 'darse cuenta de'),
(22, 'Acción y percepción', 'to seem', 'parecer'),
(22, 'Acción y percepción', 'to appear', 'aparecer'),
(22, 'Acción y percepción', 'to disappear', 'desaparecer'),
(22, 'Acción y percepción', 'to hide', 'esconderse'),
(22, 'Acción y percepción', 'to escape', 'escapar'),
(22, 'Acción y percepción', 'to chase', 'perseguir'),
(22, 'Acción y percepción', 'to shout', 'gritar'),
(22, 'Acción y percepción', 'to whisper', 'susurrar'),
(22, 'Acción y percepción', 'to cry', 'llorar'),
(22, 'Acción y percepción', 'to smile', 'sonreír'),
(22, 'Acción y percepción', 'smile', 'sonrisa'),
(22, 'Acción y percepción', 'to scream', 'chillar'),
(22, 'Acción y percepción', 'noise', 'ruido'),
(22, 'Acción y percepción', 'silence', 'silencio'),
(22, 'Acción y percepción', 'silent', 'silencioso'),
(22, 'Acción y percepción', 'darkness', 'oscuridad'),
(22, 'Acción y percepción', 'shadow', 'sombra'),
(22, 'Acción y percepción', 'to fall', 'caer'),
(22, 'Objetos y verdad', 'to drop', 'dejar caer'),
(22, 'Objetos y verdad', 'to break', 'romper'),
(22, 'Objetos y verdad', 'broken', 'roto'),
(22, 'Objetos y verdad', 'to fix', 'arreglar'),
(22, 'Objetos y verdad', 'to find', 'encontrar'),
(22, 'Objetos y verdad', 'lost', 'perdido'),
(22, 'Objetos y verdad', 'to look for', 'buscar (algo perdido)'),
(22, 'Objetos y verdad', 'to pick up', 'recoger (del suelo)'),
(22, 'Objetos y verdad', 'to throw', 'lanzar'),
(22, 'Objetos y verdad', 'to grab', 'agarrar'),
(22, 'Objetos y verdad', 'to push', 'empujar'),
(22, 'Objetos y verdad', 'to pull', 'tirar de'),
(22, 'Objetos y verdad', 'to jump', 'saltar'),
(22, 'Objetos y verdad', 'to slip', 'resbalar'),
(22, 'Objetos y verdad', 'to trip', 'tropezar'),
(22, 'Objetos y verdad', 'embarrassing', 'vergonzoso'),
(22, 'Objetos y verdad', 'embarrassed', 'avergonzado'),
(22, 'Objetos y verdad', 'to make fun of', 'burlarse de'),
(22, 'Objetos y verdad', 'to believe', 'creer'),
(22, 'Objetos y verdad', 'true', 'verdadero'),
(22, 'Objetos y verdad', 'false', 'falso'),
(22, 'Objetos y verdad', 'lie', 'mentira'),
(22, 'Objetos y verdad', 'to lie', 'mentir'),
(22, 'Objetos y verdad', 'truth', 'verdad');
