-- SEMANA 2 · Familia y descripción de personas · 42 palabras
insert into words (week, section, en, es) values
(2, 'Familia', 'mother', 'madre'),
(2, 'Familia', 'father', 'padre'),
(2, 'Familia', 'parents', 'padres'),
(2, 'Familia', 'son', 'hijo'),
(2, 'Familia', 'daughter', 'hija'),
(2, 'Familia', 'children', 'hijos'),
(2, 'Familia', 'brother', 'hermano'),
(2, 'Familia', 'sister', 'hermana'),
(2, 'Familia', 'grandfather', 'abuelo'),
(2, 'Familia', 'grandmother', 'abuela'),
(2, 'Familia', 'grandparents', 'abuelos'),
(2, 'Familia', 'grandson', 'nieto'),
(2, 'Familia', 'granddaughter', 'nieta'),
(2, 'Familia', 'uncle', 'tío'),
(2, 'Familia', 'aunt', 'tía'),
(2, 'Familia', 'cousin', 'primo/prima'),
(2, 'Familia', 'nephew', 'sobrino'),
(2, 'Familia', 'niece', 'sobrina'),
(2, 'Familia', 'husband', 'esposo'),
(2, 'Familia', 'wife', 'esposa'),
(2, 'Familia', 'couple', 'pareja'),
(2, 'Descripción física', 'baby', 'bebé'),
(2, 'Descripción física', 'boy', 'niño'),
(2, 'Descripción física', 'girl', 'niña'),
(2, 'Descripción física', 'man', 'hombre'),
(2, 'Descripción física', 'woman', 'mujer'),
(2, 'Descripción física', 'tall', 'alto'),
(2, 'Descripción física', 'short', 'bajo'),
(2, 'Descripción física', 'thin', 'delgado'),
(2, 'Descripción física', 'fat', 'gordo'),
(2, 'Descripción física', 'young', 'joven'),
(2, 'Descripción física', 'old', 'viejo'),
(2, 'Descripción física', 'pretty', 'bonita'),
(2, 'Descripción física', 'handsome', 'guapo'),
(2, 'Descripción física', 'ugly', 'feo'),
(2, 'Descripción física', 'hair', 'pelo'),
(2, 'Descripción física', 'eyes', 'ojos'),
(2, 'Descripción física', 'blond', 'rubio'),
(2, 'Descripción física', 'dark-haired', 'moreno'),
(2, 'Descripción física', 'curly', 'rizado'),
(2, 'Descripción física', 'straight (hair)', 'liso'),
(2, 'Descripción física', 'beard', 'barba');
