-- SEMANA 13 · Conectores y palabras útiles (repaso) · 60 palabras
insert into words (week, section, en, es) values
(13, 'Conectores', 'and', 'y'),
(13, 'Conectores', 'but', 'pero'),
(13, 'Conectores', 'or', 'o'),
(13, 'Conectores', 'because', 'porque'),
(13, 'Conectores', 'so', 'así que'),
(13, 'Conectores', 'then', 'entonces'),
(13, 'Conectores', 'also', 'también'),
(13, 'Conectores', 'too', 'también (al final)'),
(13, 'Conectores', 'first', 'primero'),
(13, 'Conectores', 'next (then)', 'luego'),
(13, 'Conectores', 'finally', 'finalmente'),
(13, 'Conectores', 'however', 'sin embargo'),
(13, 'Conectores', 'for example', 'por ejemplo'),
(13, 'Conectores', 'of course', 'por supuesto'),
(13, 'Conectores', 'maybe', 'quizás'),
(13, 'Conectores', 'perhaps', 'tal vez'),
(13, 'Conectores', 'really', 'de verdad'),
(13, 'Conectores', 'very', 'muy'),
(13, 'Conectores', 'quite', 'bastante'),
(13, 'Conectores', 'a little', 'un poco'),
(13, 'Cantidad y pronombres', 'a lot', 'mucho'),
(13, 'Cantidad y pronombres', 'more', 'más'),
(13, 'Cantidad y pronombres', 'less', 'menos'),
(13, 'Cantidad y pronombres', 'enough', 'suficiente'),
(13, 'Cantidad y pronombres', 'only', 'solo/solamente'),
(13, 'Cantidad y pronombres', 'both', 'ambos'),
(13, 'Cantidad y pronombres', 'all', 'todo(s)'),
(13, 'Cantidad y pronombres', 'some', 'algunos'),
(13, 'Cantidad y pronombres', 'none', 'ninguno'),
(13, 'Cantidad y pronombres', 'something', 'algo'),
(13, 'Cantidad y pronombres', 'nothing', 'nada'),
(13, 'Cantidad y pronombres', 'everything', 'todo'),
(13, 'Cantidad y pronombres', 'someone', 'alguien'),
(13, 'Cantidad y pronombres', 'no one', 'nadie'),
(13, 'Cantidad y pronombres', 'everyone', 'todos (personas)'),
(13, 'Cantidad y pronombres', 'somewhere', 'en algún lugar'),
(13, 'Cantidad y pronombres', 'here', 'aquí'),
(13, 'Cantidad y pronombres', 'there', 'allí'),
(13, 'Cantidad y pronombres', 'this', 'este'),
(13, 'Cantidad y pronombres', 'that', 'ese'),
(13, 'Preposiciones y expresiones', 'these', 'estos'),
(13, 'Preposiciones y expresiones', 'those', 'esos'),
(13, 'Preposiciones y expresiones', 'with', 'con'),
(13, 'Preposiciones y expresiones', 'without', 'sin'),
(13, 'Preposiciones y expresiones', 'about', 'sobre/acerca de'),
(13, 'Preposiciones y expresiones', 'for', 'para'),
(13, 'Preposiciones y expresiones', 'from', 'desde'),
(13, 'Preposiciones y expresiones', 'until', 'hasta'),
(13, 'Preposiciones y expresiones', 'again', 'otra vez'),
(13, 'Preposiciones y expresiones', 'together', 'juntos'),
(13, 'Preposiciones y expresiones', 'alone', 'solo (sin compañía)'),
(13, 'Preposiciones y expresiones', 'well', 'bien'),
(13, 'Preposiciones y expresiones', 'badly', 'mal'),
(13, 'Preposiciones y expresiones', 'fast', 'rápido'),
(13, 'Preposiciones y expresiones', 'slowly', 'despacio'),
(13, 'Preposiciones y expresiones', 'actually', 'en realidad'),
(13, 'Preposiciones y expresiones', 'in fact', 'de hecho'),
(13, 'Preposiciones y expresiones', 'at least', 'al menos'),
(13, 'Preposiciones y expresiones', 'by the way', 'por cierto'),
(13, 'Preposiciones y expresiones', 'I mean', 'quiero decir');
