-- SEMANA 17 · Tecnología y el futuro · 71 palabras
-- Nota: el título original decía "72 palabras"; transcribiendo la tabla con cuidado
-- solo conté 71. Si tienes el listado en texto plano, dime y reviso la que falte.
insert into words (week, section, en, es) values
(17, 'Dispositivos y hardware', 'technology', 'tecnología'),
(17, 'Dispositivos y hardware', 'computer', 'ordenador/computadora'),
(17, 'Dispositivos y hardware', 'laptop', 'portátil'),
(17, 'Dispositivos y hardware', 'tablet', 'tableta'),
(17, 'Dispositivos y hardware', 'smartphone', 'teléfono inteligente'),
(17, 'Dispositivos y hardware', 'screen', 'pantalla'),
(17, 'Dispositivos y hardware', 'keyboard', 'teclado'),
(17, 'Dispositivos y hardware', 'mouse (computer)', 'ratón (informática)'),
(17, 'Dispositivos y hardware', 'printer', 'impresora'),
(17, 'Dispositivos y hardware', 'charger', 'cargador'),
(17, 'Dispositivos y hardware', 'battery', 'batería'),
(17, 'Dispositivos y hardware', 'headphones', 'auriculares'),
(17, 'Dispositivos y hardware', 'speaker', 'altavoz'),
(17, 'Dispositivos y hardware', 'microphone', 'micrófono'),
(17, 'Dispositivos y hardware', 'file', 'archivo'),
(17, 'Dispositivos y hardware', 'folder', 'carpeta'),
(17, 'Dispositivos y hardware', 'document', 'documento'),
(17, 'Dispositivos y hardware', 'to download', 'descargar'),
(17, 'Dispositivos y hardware', 'app', 'aplicación'),
(17, 'Dispositivos y hardware', 'software', 'software'),
(17, 'Dispositivos y hardware', 'program', 'programa'),
(17, 'Dispositivos y hardware', 'to program', 'programar'),
(17, 'Dispositivos y hardware', 'internet', 'internet'),
(17, 'Dispositivos y hardware', 'wifi', 'wifi'),
(17, 'Internet y cuentas', 'website', 'sitio web'),
(17, 'Internet y cuentas', 'web page', 'página web'),
(17, 'Internet y cuentas', 'link', 'enlace'),
(17, 'Internet y cuentas', 'to click', 'hacer clic'),
(17, 'Internet y cuentas', 'to search', 'buscar'),
(17, 'Internet y cuentas', 'search engine', 'buscador'),
(17, 'Internet y cuentas', 'inbox', 'bandeja de entrada'),
(17, 'Internet y cuentas', 'to receive', 'recibir'),
(17, 'Internet y cuentas', 'attachment', 'archivo adjunto'),
(17, 'Internet y cuentas', 'password', 'contraseña'),
(17, 'Internet y cuentas', 'username', 'nombre de usuario'),
(17, 'Internet y cuentas', 'account', 'cuenta (perfil)'),
(17, 'Internet y cuentas', 'to log in', 'iniciar sesión'),
(17, 'Internet y cuentas', 'to log out', 'cerrar sesión'),
(17, 'Internet y cuentas', 'to sign up', 'registrarse'),
(17, 'Internet y cuentas', 'social media', 'redes sociales'),
(17, 'Internet y cuentas', 'to post', 'publicar (en redes)'),
(17, 'Internet y cuentas', 'to share', 'compartir'),
(17, 'Internet y cuentas', 'to follow', 'seguir (en redes)'),
(17, 'Internet y cuentas', 'follower', 'seguidor'),
(17, 'Internet y cuentas', 'to like (a post)', 'dar me gusta'),
(17, 'Internet y cuentas', 'message', 'mensaje'),
(17, 'Internet y cuentas', 'video call', 'videollamada'),
(17, 'Conexión, IA y datos', 'connection', 'conexión'),
(17, 'Conexión, IA y datos', 'to connect', 'conectar'),
(17, 'Conexión, IA y datos', 'to disconnect', 'desconectar'),
(17, 'Conexión, IA y datos', 'online', 'en línea'),
(17, 'Conexión, IA y datos', 'offline', 'sin conexión'),
(17, 'Conexión, IA y datos', 'to turn on', 'encender'),
(17, 'Conexión, IA y datos', 'to turn off', 'apagar'),
(17, 'Conexión, IA y datos', 'to charge', 'cargar (batería)'),
(17, 'Conexión, IA y datos', 'to update', 'actualizar'),
(17, 'Conexión, IA y datos', 'update', 'actualización'),
(17, 'Conexión, IA y datos', 'to delete', 'borrar'),
(17, 'Conexión, IA y datos', 'to save (a file)', 'guardar'),
(17, 'Conexión, IA y datos', 'robot', 'robot'),
(17, 'Conexión, IA y datos', 'artificial intelligence', 'inteligencia artificial'),
(17, 'Conexión, IA y datos', 'device', 'dispositivo'),
(17, 'Conexión, IA y datos', 'gadget', 'aparato'),
(17, 'Conexión, IA y datos', 'useful', 'útil'),
(17, 'Conexión, IA y datos', 'useless', 'inútil'),
(17, 'Conexión, IA y datos', 'modem', 'módem'),
(17, 'Conexión, IA y datos', 'digital', 'digital'),
(17, 'Conexión, IA y datos', 'data', 'datos'),
(17, 'Conexión, IA y datos', 'to type', 'teclear'),
(17, 'Conexión, IA y datos', 'to print', 'imprimir'),
(17, 'Conexión, IA y datos', 'the cloud', 'la nube (informática)');
