-- SEMANA 8 · La ciudad, tiendas y lugares · 60 palabras
insert into words (week, section, en, es) values
(8, 'La ciudad y tiendas', 'town', 'pueblo grande'),
(8, 'La ciudad y tiendas', 'village', 'pueblo'),
(8, 'La ciudad y tiendas', 'street', 'calle'),
(8, 'La ciudad y tiendas', 'avenue', 'avenida'),
(8, 'La ciudad y tiendas', 'square', 'plaza'),
(8, 'La ciudad y tiendas', 'corner', 'esquina'),
(8, 'La ciudad y tiendas', 'building', 'edificio'),
(8, 'La ciudad y tiendas', 'shop/store', 'tienda'),
(8, 'La ciudad y tiendas', 'supermarket', 'supermercado'),
(8, 'La ciudad y tiendas', 'bakery', 'panadería'),
(8, 'La ciudad y tiendas', 'butcher''s', 'carnicería'),
(8, 'La ciudad y tiendas', 'pharmacy', 'farmacia'),
(8, 'La ciudad y tiendas', 'bank', 'banco'),
(8, 'La ciudad y tiendas', 'post office', 'oficina de correos'),
(8, 'La ciudad y tiendas', 'hospital', 'hospital'),
(8, 'La ciudad y tiendas', 'school', 'escuela'),
(8, 'La ciudad y tiendas', 'university', 'universidad'),
(8, 'La ciudad y tiendas', 'library', 'biblioteca'),
(8, 'La ciudad y tiendas', 'museum', 'museo'),
(8, 'La ciudad y tiendas', 'church', 'iglesia'),
(8, 'Más lugares', 'park', 'parque'),
(8, 'Más lugares', 'cinema', 'cine'),
(8, 'Más lugares', 'theater', 'teatro'),
(8, 'Más lugares', 'restaurant', 'restaurante'),
(8, 'Más lugares', 'café', 'cafetería'),
(8, 'Más lugares', 'hotel', 'hotel'),
(8, 'Más lugares', 'market', 'mercado'),
(8, 'Más lugares', 'shopping mall', 'centro comercial'),
(8, 'Más lugares', 'police station', 'comisaría'),
(8, 'Más lugares', 'fire station', 'parque de bomberos'),
(8, 'Más lugares', 'town hall', 'ayuntamiento'),
(8, 'Más lugares', 'bridge', 'puente'),
(8, 'Más lugares', 'river', 'río'),
(8, 'Más lugares', 'traffic light', 'semáforo'),
(8, 'Más lugares', 'crosswalk', 'paso de peatones'),
(8, 'Más lugares', 'sidewalk', 'acera'),
(8, 'Más lugares', 'road', 'carretera'),
(8, 'Más lugares', 'bus stop', 'parada de bus'),
(8, 'Más lugares', 'train station', 'estación de tren'),
(8, 'Más lugares', 'airport', 'aeropuerto'),
(8, 'Direcciones', 'gas station', 'gasolinera'),
(8, 'Direcciones', 'parking lot', 'aparcamiento'),
(8, 'Direcciones', 'to turn', 'girar'),
(8, 'Direcciones', 'left', 'izquierda'),
(8, 'Direcciones', 'right', 'derecha'),
(8, 'Direcciones', 'straight ahead', 'todo recto'),
(8, 'Direcciones', 'near', 'cerca'),
(8, 'Direcciones', 'far', 'lejos'),
(8, 'Direcciones', 'next to', 'al lado de'),
(8, 'Direcciones', 'in front of', 'delante de'),
(8, 'Direcciones', 'behind', 'detrás de'),
(8, 'Direcciones', 'between', 'entre'),
(8, 'Direcciones', 'opposite', 'enfrente de'),
(8, 'Direcciones', 'map', 'mapa'),
(8, 'Direcciones', 'to cross', 'cruzar'),
(8, 'Direcciones', 'to get lost', 'perderse'),
(8, 'Direcciones', 'to ask for directions', 'pedir indicaciones'),
(8, 'Direcciones', 'busy', 'concurrido'),
(8, 'Direcciones', 'quiet', 'tranquilo'),
(8, 'Direcciones', 'place', 'lugar');
